import { useState } from 'react';
import { configureAiCosts, type Workspace, type AiCosts } from '../services/agentApi';
const defaults: AiCosts = { taskMinor: 500, enabled: false, dailyMinor: 500, monthlyMinor: 5000, callMinor: 500, ceilings: { text: 100, research: 200, vision: 200, image: 500 }, dayMinor: 0, monthMinor: 0, entries: [] };
const money = (v: number) => (v / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
export function AiCostsPanel({ workspace, busy, mutate }: { workspace: Workspace; busy: boolean; mutate: (op: () => Promise<Workspace>, success?: string) => Promise<Workspace | null> }) {
 const current = workspace.aiCosts || defaults;
 const [draft, setDraft] = useState<AiCosts | null>(null);
 const value = draft || current;
 const groups = new Map<string, number>();
 for (const entry of current.entries) { const key = entry.agentId + ' · ' + entry.model; groups.set(key, (groups.get(key) || 0) + (entry.exposureMinor ?? entry.reservedMinor)); }
 return <section className="aw-panel" id="ai-costs"><h2>Orçamento de IA</h2><p>Exposição de orçamento hoje: {money(current.dayMinor)} / {money(current.dailyMinor)} · mês: {money(current.monthMinor)} / {money(current.monthlyMinor)}</p><p>Custos confirmados hoje: {current.day?.hasConfirmedCosts ? money(current.day.confirmedMinor) : 'A apurar'} · chamadas pendentes: {money(current.day?.reservedMinor || 0)} · custos a apurar (reserva conservadora): {money(current.day?.unknownMinor ?? current.dayMinor)}</p><p className="aw-caption">Reservas declaradas por chamada, não fatura real nem lucro. Custos ainda não confirmados mantêm a reserva conservadora, inclusive respostas concluídas sem fatura. Chamadas bloqueadas antes do envio não gastam nem retêm reserva. Aumentar uma reserva aumenta a exposição; para autorizar mais gasto, revise os limites. Limites em UTC. Configure reservas conservadoras e também o limite no provedor. Modelos por função são escolhidos em Conexões → IA. Decisões usam o principal, trabalhadores usam o econômico. Cache de texto por 24 horas.</p><form className="aw-form" onSubmit={e => { e.preventDefault(); void mutate(() => configureAiCosts(value), 'Orçamento salvo.'); }}><label className="aw-checkbox"><input type="checkbox" checked={value.enabled} onChange={e => setDraft({ ...value, enabled: e.target.checked })} />Autorizar chamadas dentro do orçamento</label>{(['dailyMinor', 'monthlyMinor', 'callMinor', 'taskMinor'] as const).map(k => <label key={k}>{k === 'dailyMinor' ? 'Limite diário' : k === 'monthlyMinor' ? 'Limite mensal' : k === 'taskMinor' ? 'Limite por tarefa' : 'Limite por chamada'} (centavos)<input type="number" min="1" max="10000000" value={value[k]} onChange={e => setDraft({ ...value, [k]: Number(e.target.value) })} required /></label>)}{Object.entries(value.ceilings).map(([k,v]) => <label key={k}>Reserva de {k} (centavos)<input type="number" min="1" max="10000000" value={v} onChange={e => setDraft({ ...value, ceilings: { ...value.ceilings, [k]: Number(e.target.value) } })} required /></label>)}<button className="aw-button" disabled={busy}>Salvar orçamento</button></form><details><summary>Exposição por agente, modelo e tarefa (últimas 100 chamadas)</summary>{[...groups].map(([k,v]) => <p key={k}>{k}: {money(v)}</p>)}{current.entries.map(e => <p className="aw-caption" key={e.id}>{e.taskId} · {e.actualModel||e.model} · {e.kind} · exposição: {money(e.exposureMinor ?? e.reservedMinor)} · confirmado: {e.confirmedMinor == null ? 'A apurar' : money(e.confirmedMinor)} · {e.tokens} tokens · {e.status} · estimativa de texto: {e.estimatedTextUsd==null?'A apurar':`US$ ${e.estimatedTextUsd.toFixed(5)}`} (não inclui ferramentas/imagens nem câmbio)</p>)}</details></section>;
}
