import type { Workspace } from '../services/agentApi';
export function AstraConsole({ workspace }: { workspace: Workspace }) {
  const decisions = workspace.autonomy.projects.flatMap(p => (p.decisions || []).map(d => ({ ...d, projectName: p.name }))).sort((a, b) => b.observedAt.localeCompare(a.observedAt)).slice(0, 5);
  const latest = decisions[0];
  const active = workspace.autonomy.projects.find(p => p.status === 'planning');
  return <section className="aw-panel aw-astra-console" id="astra"><div className="aw-section-title"><div><p className="aw-eyebrow">ASTRA / ORQUESTRAÇÃO COM EVIDÊNCIAS</p><h2>Por que escolhi esta oportunidade?</h2></div><span className="aw-badge">{active ? 'ANALISANDO' : latest ? 'DECISÃO REGISTRADA' : 'SEM DECISÃO'}</span></div><p className="aw-caption">Astra representa o coordenador Orion. Modelo conectado: {workspace.settings.decisionModel || workspace.settings.model}. O painel mostra registros reais; não executa uma nova chamada de IA ao abrir.</p>{active && <p>{active.name}: {active.phase}</p>}{!latest && <div className="aw-notice"><p>Nenhuma decisão comercial registrada. Conecte a IA e autorize um projeto em Autonomia para pesquisar oportunidades. O plano de experimento sozinho não inicia a pesquisa.</p></div>}
    {decisions.map((d, index) => <details key={d.id} open={index === 0}><summary>{d.selected?.title || 'Nenhuma opção passou pelos critérios'} · {new Date(d.observedAt).toLocaleString('pt-BR')}</summary><p className="aw-caption">Projeto: {d.projectName} · Modelo no momento: {d.model || 'Não registrado nesta decisão antiga'}</p>{d.selected && <><h3>Motivo registrado</h3><p>{d.selected.rationale}</p><h3>O que ainda é incerto</h3><p>{d.selected.uncertainty}</p><h3>Próximo teste proposto</h3><p>{d.selected.test}</p><p className="aw-caption">{d.selected.score}/100 é uma pontuação heurística, não uma chance de lucro. A escolha considera evidência, viabilidade, distribuição e ferramentas disponíveis.</p>{d.selected.execution && <p>Execução: {d.selected.execution.status === 'executable' ? 'Ferramentas disponíveis e autorizadas' : d.selected.execution.status === 'preparation' ? 'Somente preparação privada' : 'Bloqueada por ferramentas ausentes'}.</p>}</>}
      <h3>Alternativas consideradas</h3><ul>{d.candidates.map(c => <li key={c.id}><strong>{c.title} · {c.score}/100</strong><p className="aw-caption">{c.rationale} {c.execution?.missing.map(m => m.reason).join(' ')}</p></li>)}</ul><h3>Resultados usados nesta decisão</h3>{d.learning ? <><p>{d.learning.experiments.length} experimento(s) no resumo observado em {new Date(d.learning.observedAt).toLocaleString('pt-BR')}. {d.learning.experiments.filter(e => e.metrics.costComplete).length} com custos revisados naquele momento.</p><p className="aw-caption">{d.learning.note} Valores atualizados agora aparecem em Experimentos; este registro conserva a evidência disponível quando a decisão foi tomada.</p></> : <p className="aw-caption">Decisão anterior ao registro de aprendizado financeiro; não atribuir resultados que ainda não existiam.</p>}
      <h3>Memória consultada</h3>{d.memoryUsed ? <ul>{d.memoryUsed.map(n => <li key={n.id}>{n.title} · {n.origin}</li>)}</ul> : <p className="aw-caption">Esta decisão não registrou consulta ao segundo cérebro.</p>}<a href="#knowledge">Consultar notas disponíveis</a><h3>Fontes da pesquisa</h3><ul>{d.sources.filter(s => /^https?:\/\//.test(s.url)).map((s, i) => <li key={i}><a href={s.url} target="_blank" rel="noreferrer">{s.title || s.url}</a></li>)}</ul></details>)}
    <div className="aw-actions"><a className="aw-button aw-secondary" href="#autonomy">Abrir projetos autônomos</a><a className="aw-button aw-secondary" href="#experiments">Conferir resultados comerciais</a></div>
    <details><summary>Vídeos e próximos canais: o que falta?</summary><p>Exportação de MP4 e legendas sincronizadas ainda não estão implementadas. CapCut, YouTube e TikTok ainda não estão conectados; kits privados continuam sendo roteiros, não vídeos publicados.</p><p>O caminho é: produção de mídia original e sincronização de legendas, depois aplicativo oficial com OAuth, consentimento de publicação, armazenamento protegido e confirmação de envio. A auditoria das plataformas pode limitar vídeos a modo privado.</p><div className="aw-actions"><a href="https://developers.tiktok.com/docs/en/content-posting-api-get-started" target="_blank" rel="noreferrer">Requisitos oficiais TikTok</a><a href="https://developers.google.com/youtube/v3/docs/videos/insert" target="_blank" rel="noreferrer">Requisitos oficiais YouTube</a></div><p className="aw-caption">Sem credenciais do aplicativo e autorização da conta, não há publicação automática nesses canais. Escrever o nome de um canal no plano não o conecta.</p></details>
  </section>;
}
