import { ItchReadiness } from './ItchReadiness';
import { ItchRelease } from './ItchRelease';
import { useState } from 'react';
import type { FormEvent } from 'react';
import { Store, Upload, RefreshCw } from 'lucide-react';
import { agentApi, productionLabels } from '../services/agentApi';
import type { Workspace, CommerceSettings } from '../services/agentApi';
type Props = { workspace: Workspace; busy: boolean; mutate: (operation: () => Promise<Workspace>, success?: string) => Promise<Workspace | null> };
const amount = (minor: number, currency: string) => `${(minor / 100).toFixed(2)} ${currency}`;
export function CommercePanel({ workspace, busy, mutate }: Props) {
  const [key, setKey] = useState('');
  const c = workspace.commerce;
  const [settings, setSettings] = useState<CommerceSettings>({ autoPublish: c?.autoPublish || false, background: c?.background || false, maxUploads: c?.maxUploads || 3, targets: { sprites: c?.targets.sprites?.id || '', model3d: c?.targets.model3d?.id || '' }, license: c?.license || '' });
  async function connect(e: FormEvent) { e.preventDefault(); const result = await mutate(() => agentApi.connectStore(key), 'Loja conectada. Escolha páginas, licença e autorização.'); if (result) setKey(''); }
  async function configure(e: FormEvent) { e.preventDefault(); await mutate(() => agentApi.configureStore(settings), 'Configuração comercial salva por até 72 horas.'); }
  const pages = c?.games.filter(game => game.classification === 'assets') || [];
  const packs = workspace.missions.filter(m => ['sprites', 'model3d'].includes(m.kind) && m.hasArtifact && ['review', 'approved'].includes(m.status));
  return <section className="aw-panel" id="commerce"><div className="aw-section-title"><div><p className="aw-eyebrow">DISTRIBUIÇÃO / ITCH.IO</p><h2><Store size={21} /> Loja e resultados reais</h2></div><span className="aw-badge">{c?.configured ? 'LOJA CONECTADA' : 'SEM LOJA'}</span></div>
    <p className="aw-caption">Para packs de jogos. Crie uma página de assets, inicialmente em rascunho, para cada coleção e configure preço/recebimento uma vez no itch.io. A central envia arquivos autorizados; não cria páginas, altera visibilidade nem muda preços. Thumbnails ficam fora deste canal.</p>
    <details open={!c?.configured}><summary>Conectar minha conta</summary><ol><li>Crie sua conta no itch.io e configure recebimento na própria plataforma.</li><li>Em Upload new project, escolha Game assets, adicione apresentação/licença, defina preço e mantenha em rascunho até revisar a oferta.</li><li>Gere uma chave no itch.io e cole abaixo. A chave permite acessar sua conta: ela fica criptografada no servidor.</li></ol><a className="aw-button aw-secondary" href="https://itch.io/user/settings/api-keys" target="_blank" rel="noreferrer">Abrir chaves itch.io</a><form className="aw-form" onSubmit={connect}><label>Chave itch.io<input type="password" value={key} onChange={e => setKey(e.target.value)} autoComplete="off" maxLength={1000} required /></label><button className="aw-button" disabled={busy}>Conectar / trocar chave</button></form></details>
    {c?.configured && <><ItchReadiness key={c.readiness?.checkedAt || "initial"} workspace={workspace} busy={busy} mutate={mutate}/><form className="aw-form" onSubmit={configure}><div className="aw-columns">{(['sprites', 'model3d'] as const).map(kind => <label key={kind}>Destino: {productionLabels[kind]}<select value={settings.targets[kind] || ''} onChange={e => setSettings(current => ({ ...current, targets: { ...current.targets, [kind]: e.target.value } }))}><option value="">Não publicar este formato</option>{pages.map(game => <option key={game.id} value={game.id}>{game.title}{game.published ? ' · pública' : ' · rascunho'}</option>)}</select></label>)}</div>{!pages.length && <p className="aw-caption">Nenhuma página de assets encontrada. Crie um rascunho e clique em Sincronizar loja.</p>}<label>Licença e condições que irão com cada pack<textarea rows={4} maxLength={4000} value={settings.license} onChange={e => setSettings(current => ({ ...current, license: e.target.value }))} placeholder="Defina uso comercial, modificações, redistribuição, suporte e limitações…" required /></label><label>Limite de tentativas de upload<input type="number" min={1} max={20} value={settings.maxUploads} onChange={e => setSettings(current => ({ ...current, maxUploads: Number(e.target.value) }))} required /></label><label className="aw-checkbox"><input type="checkbox" checked={settings.autoPublish} onChange={e => setSettings(current => ({ ...current, autoPublish: e.target.checked }))} /> Permitir envio automático somente de versões aprovadas e com autorização comercial específica vigente</label><label className="aw-checkbox"><input type="checkbox" checked={settings.background} onChange={e => setSettings(current => ({ ...current, background: e.target.checked }))} /> Autorizar uploads e consulta de métricas sem manter a aba aberta, por até 72 horas</label><small>O upload pode tornar o pack disponível aos compradores da página. Confira a qualidade e se a coleção, licença e preço são adequados. Falhas não são repetidas automaticamente.</small><button className="aw-button" disabled={busy}>Salvar autorização e destinos</button></form>
      <p className="aw-caption">{c.uploads}/{c.maxUploads} tentativas utilizadas · envio automático {c.autoPublish ? 'autorizado' : 'pausado'} · {c.expiresAt ? `autorização até ${new Date(c.expiresAt).toLocaleString('pt-BR')}` : 'configure a autorização'}</p>{c.error && <p className="aw-error" role="alert">{c.error}</p>}<div className="aw-actions"><button className="aw-button aw-secondary" disabled={busy} onClick={() => void mutate(agentApi.syncStore, 'Métricas consultadas diretamente no itch.io.')}><RefreshCw size={15} /> Sincronizar loja</button><button className="aw-button aw-secondary" disabled={busy} onClick={() => void mutate(agentApi.disconnectStore, 'Loja desconectada; novos uploads suspensos. Uploads já iniciados podem concluir.')}>Desconectar loja</button></div>
      <h3>Totais retornados pela plataforma</h3><p className="aw-caption">São totais históricos de cada página, não de cada pack. Receita não desconta todos os custos e não é lucro. Dados ausentes aparecem como não informados.</p>{c.games.map(game => <article className="aw-project" key={game.id}><a href={game.url} target="_blank" rel="noreferrer">{game.title}</a><p>Visitas: {game.views ?? 'não informado'} · Compras: {game.purchases ?? 'não informado'} · Downloads: {game.downloads ?? 'não informado'}</p><p>Receita informada: {game.earnings.length ? game.earnings.map(item => amount(item.grossMinor, item.currency)).join(' / ') : 'não informada'}</p><small>Consulta: {new Date(game.observedAt).toLocaleString('pt-BR')} · itch.io API</small></article>)}
      <h3>Packs e uploads</h3>{!packs.length && <p className="aw-caption">Os packs produzidos aparecerão aqui.</p>}{packs.map(m => <article className="aw-project" key={m.id}><h3>{m.title}</h3><p>{m.publication?.status === 'uploaded' ? 'Upload confirmado — confira visibilidade na página' : m.publication?.status === 'uploading' ? 'Upload iniciado' : m.publication?.status === 'uncertain' ? 'Resultado incerto — confira o canal na loja' : 'Ainda não enviado'}</p>{m.publication?.target && <a href={m.publication.target.url} target="_blank" rel="noreferrer">{m.publication.target.title}</a>}{m.publication?.error && <p className="aw-error">{m.publication.error}</p>}{m.publication?.channel && <p className="aw-caption">Canal: {m.publication.channel}</p>}{m.publication?.status !== 'uploaded' && <ItchRelease mission={m} workspace={workspace} busy={busy} mutate={mutate}/>}
{m.publication?.status !== 'uploaded' && m.publication?.status !== 'uploading' && <button className="aw-button" disabled={busy || !c.targets[m.kind] || m.status!=="approved" || !m.itchRelease} onClick={() => void mutate(() => agentApi.publishPack(m.id), 'Upload confirmado. Visibilidade e preço são os da página itch.io.')}><Upload size={15} /> {m.publication?.status === 'uncertain' ? 'Conferi na loja; reenviar no mesmo canal' : 'Enviar pack à loja'}</button>}{m.publication?.status === 'uploading' && <button className="aw-button aw-secondary" disabled={busy} onClick={() => void mutate(() => agentApi.recoverUpload(m.id), 'Upload marcado como incerto. Confira o canal antes de reenviar.')}>Recuperar upload interrompido há mais de 4 minutos</button>}</article>)}
    </>}
  </section>;
}
