import type { Workspace } from '../services/agentApi';
export function ConnectionsPanel({workspace:w}:{workspace:Workspace}) {
 const cards=[
 {name:'Etsy',status:w.etsy?.connected?'API oficial conectada':'Configuração / autorização necessária',detail:w.etsy?.error||'Listing digital pela API após revisão. O fluxo assistido permanece disponível.',href:'#etsy',action:'Configurar Etsy',ready:w.etsy?.connected},
 {name:'OpenAI', status:w.settings.configured?'Chave validada ao salvar':'Não conectada',detail:w.settings.configured?(w.aiCosts?.enabled?'Orçamento autorizado. Você pode iniciar uma tarefa.':'Falta autorizar o orçamento para executar.'):'Necessária para produzir. Sua assinatura ChatGPT não inclui a API.',href:'#settings',action:w.settings.configured?'Gerenciar chave':'Conectar IA',ready:w.settings.configured},
 {name:'Orçamento',status:w.aiCosts?.enabled?'Autorizado':'Chamadas bloqueadas',detail:'Defina o limite antes de iniciar. Reservas não são a fatura do provedor.',href:'#costs',action:'Configurar limite',ready:w.aiCosts?.enabled},
 {name:'Stripe / loja',status:w.shop?.configured?(w.shop.livemode?'Conta real conectada':'Modo de teste'):'Não conectada',detail:w.shop?.error || (w.shop?.enabled?'Catálogo aberto. Confira produtos e preços.':'Abra a loja após configurar licença e preços.'),href:'#shop',action:'Configurar loja',ready:w.shop?.enabled&&w.shop.livemode},
 {name:'Divulgação',status:`${w.marketing?.channels.filter(c=>c.configured).length || 0} canais conectados`,detail:w.marketing?.error || (w.marketing?.enabled?'Envios autorizados até a validade mostrada em Divulgação.':'Conectar um canal não inicia os envios. Autorize quando a loja estiver pronta.'),href:'#marketing',action:'Escolher canais',ready:w.marketing?.enabled},
 {name:'itch.io',status:w.commerce?.configured?'Credencial salva':'Opcional · não conectado',detail:w.commerce?.error || 'Para packs de jogos. Escolha a página de destino e autorize os uploads.',href:'#commerce',action:'Configurar itch.io',ready:w.commerce?.configured},
 {name:'Segundo cérebro',status:w.knowledge?.configured?'Token salvo':'Leitura pública disponível',detail:w.knowledge?.error || (w.knowledge?.enabled?'Escrita autorizada por tempo limitado.':'Importar referências não exige token. Escrita exige autorização separada.'),href:'#knowledge',action:'Abrir memória',ready:w.knowledge?.enabled},
 {name:'GitHub / HubLoan',status:w.engineering?.configured?'Token salvo':'Opcional · não conectado',detail:w.engineering?.error || 'Propostas de melhoria. Merge depende da sua aprovação; não controla o terminal do Codespace.',href:'#improvements',action:'Configurar melhorias',ready:w.engineering?.configured},
 ];
 return <section className="aw-panel"><h2>O que está conectado?</h2><p>Comece por OpenAI e orçamento. Os outros serviços entram quando você precisar vender, divulgar ou guardar referências.</p><div className="aw-connection-grid">{cards.map(c=><article key={c.name}><span className={`aw-connection-state ${c.ready?'is-ready':''}`}>{c.status}</span><h3>{c.name}</h3><p>{c.detail}</p><a className="aw-button aw-secondary" href={c.href}>{c.action}</a></article>)}</div><p className="aw-caption">Os estados vêm do servidor. Uma credencial salva pode expirar no provedor; erros da última operação aparecem aqui e na configuração.</p></section>;
}
