import { useState } from 'react';
import type { FormEvent } from 'react';
import { Cpu, Pause } from 'lucide-react';
import { agentApi } from '../services/agentApi';
import type { Workspace, EngineeringSettings } from '../services/agentApi';
type Props = { workspace: Workspace; busy: boolean; mutate: (operation: () => Promise<Workspace>, success?: string) => Promise<Workspace | null> };
const states: Record<string, string> = { queued: 'Na fila', running: 'Em andamento', proposed: 'PR rascunho', failed: 'Interrompida', uncertain: 'Conferir no GitHub', paused: 'Pausada', closed: 'Tentativa encerrada' };
const checks: Record<string, string> = { unknown: 'Testes não confirmados', pending: 'Testes em andamento', passed: 'CI passou', failed: 'CI não passou' };
export function EngineeringPanel({ workspace, busy, mutate }: Props) {
  const engineering = workspace.engineering;
  const [key, setKey] = useState(''), [authorize, setAuthorize] = useState(false);
  const [checked, setChecked] = useState<Record<string, boolean>>({});
  const [settings, setSettings] = useState<EngineeringSettings>({ enabled: false, maxJobs: engineering?.maxJobs || 1, maxCalls: engineering?.maxCalls || 3 });
  async function connect(event: FormEvent) { event.preventDefault(); const result = await mutate(() => agentApi.connectEngineering(key, authorize), 'GitHub conectado. Configure a autorização de propostas abaixo.'); if (result) { setKey(''); setAuthorize(false); } }
  async function configure(event: FormEvent) { event.preventDefault(); await mutate(() => agentApi.configureEngineering(settings), 'Autorização de engenharia salva por até 72 horas.'); }
  const running = engineering?.jobs.some(j => ['queued', 'running'].includes(j.status));
  const uncertain = engineering?.jobs.some(j => j.status === 'uncertain');
  const authorized = engineering?.authorized;
  return <section className="aw-panel" id="improvements"><div className="aw-section-title"><div><p className="aw-eyebrow">DIAGNÓSTICO / PLANO / CÓDIGO / REVISÃO</p><h2><Cpu size={21} /> Melhorias e autocodificação</h2></div><span className="aw-badge">{engineering?.enabled ? 'PROPOSTAS AUTOMÁTICAS' : 'PROPOSTAS MANUAIS'}</span></div>
    <p className="aw-caption">Diagnósticos usam os dados deste espaço. Os agentes podem planejar uma melhoria, gerar código e abrir um PR rascunho no próprio HubLoan. Nesta etapa, somente três melhorias de interface/documentação estão disponíveis. O terminal do Codespaces, merge e publicação automática de código permanecem indisponíveis.</p>
    <div className="aw-columns">{engineering?.roles.map(role => <article className="aw-project" key={role.id}><h3>{role.name}</h3><p>{role.role}</p></article>)}</div>
    <h3>Possíveis melhorias</h3><div className="aw-columns">{engineering?.diagnostics.map(d => <article className="aw-project" key={d.id}><span className="aw-badge">Prioridade {d.priority}</span><h3>{d.title}</h3><p>{d.evidence}</p>{d.action && <a className="aw-button aw-secondary" href={d.action}>Ver configuração / dados</a>}{d.type === 'code' && <><details><summary>Arquivos autorizados</summary>{d.files?.map(f => <p key={f}><code>{f}</code></p>)}</details><button className="aw-button" disabled={busy || !authorized || running || uncertain || (engineering?.usedCalls || 0) + 3 > (engineering?.maxCalls || 3) || (engineering?.usedJobs || 0) >= (engineering?.maxJobs || 1) || engineering?.jobs.some(j => j.taskId === d.id && !['failed', 'paused'].includes(j.status))} onClick={() => void mutate(() => agentApi.proposeImprovement(d.id), 'Proposta na fila: três chamadas reservadas. Acompanhe as etapas abaixo.')}>Gerar proposta · 3 chamadas</button></>}</article>)}</div>
    <details open={!engineering?.configured}><summary>Conectar GitHub para propor mudanças</summary><ol><li>Crie um <a href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noreferrer">token fine-grained</a> com expiração curta, somente para <strong>greenspyder/HubLoan</strong>.</li><li>Permissões de repositório: Contents e Pull requests em Read and write; Checks e Actions em Read-only. Metadata é automática. Não conceda administração, workflows ou Codespaces.</li><li>Conecte também OpenAI em “Conectar IA”. Cada proposta pode usar três chamadas pagas. Não envie tokens pelo chat.</li></ol><form className="aw-form" onSubmit={connect}><label>Token GitHub<input type="password" autoComplete="off" maxLength={400} value={key} onChange={e => setKey(e.target.value)} required placeholder="github_pat_…" /></label><label className="aw-checkbox"><input type="checkbox" checked={authorize} onChange={e => setAuthorize(e.target.checked)} /> Sou responsável pelo repositório e autorizo ler os arquivos e criar branches e PRs rascunho</label><small>O token fica criptografado no servidor e não é enviado aos modelos. A conexão confirma acesso ao repositório; permissões insuficientes podem impedir o envio.</small><button className="aw-button" disabled={busy || !authorize}>Conectar GitHub</button></form></details>
    {engineering?.configured && <form className="aw-form" onSubmit={configure}><div className="aw-columns"><label>Máximo de propostas nesta autorização<input type="number" min={1} max={3} required value={settings.maxJobs} onChange={e => setSettings(s => ({ ...s, maxJobs: Number(e.target.value) }))} /></label><label>Máximo de chamadas reservadas<input type="number" min={3} max={9} required value={settings.maxCalls} onChange={e => setSettings(s => ({ ...s, maxCalls: Number(e.target.value) }))} /></label></div><label className="aw-checkbox"><input type="checkbox" checked={settings.enabled} onChange={e => setSettings(s => ({ ...s, enabled: e.target.checked }))} /> Selecionar e propor automaticamente as melhorias disponíveis por até 72 horas</label><p className="aw-caption">Desmarcado: você escolhe cada proposta nos cartões. Cada tentativa reserva três chamadas antes de começar, mesmo se interrompida. Isso não é teto financeiro. Defina limites de gastos no provedor. Processamento depende de o servidor estar ativo; hospedagem que adormece interrompe o trabalho.</p><div className="aw-actions"><button className="aw-button" disabled={busy || running || uncertain || !workspace.settings.configured}>Salvar autorização e limites</button><button type="button" className="aw-button aw-secondary" disabled={busy} onClick={() => void mutate(agentApi.pauseEngineering, 'Engenharia pausada e autorização revogada. Confira branches já enviadas.')}><Pause size={15} /> Pausar agora</button><button type="button" className="aw-button aw-secondary" disabled={busy} onClick={() => void mutate(agentApi.disconnectEngineering, 'GitHub desconectado. Branches e PRs existentes permanecem no repositório.')}>Desconectar GitHub</button></div></form>}
    <p className="aw-caption">{engineering?.usedJobs || 0}/{engineering?.maxJobs || 1} propostas · {engineering?.usedCalls || 0}/{engineering?.maxCalls || 3} chamadas reservadas{engineering?.expiresAt ? ` · validade até ${new Date(engineering.expiresAt).toLocaleString('pt-BR')}` : ''}. Pausar não desfaz operações já enviadas ao GitHub.</p>{engineering?.error && <p className="aw-error" role="alert">{engineering.error}</p>}
    <h3>Propostas e validação</h3>{!engineering?.jobs.length && <p className="aw-caption">Nenhuma proposta gerada. Diagnóstico não significa execução de IA.</p>}{engineering?.jobs.map(j => <article className="aw-project" key={j.id}><h3>{j.title}</h3><p>{states[j.status] || j.status} · {j.phase}</p><p><code>{j.branch}</code></p>{j.plan && <details><summary>Plano do Orion</summary><p style={{ whiteSpace: 'pre-wrap' }}>{j.plan}</p></details>}{j.edits && <details><summary>Alterações propostas pelo Forge</summary>{j.edits.map((edit, i) => <div key={i}><h4>{edit.path}</h4><p>Antes</p><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{edit.before || '(arquivo novo)'}</pre><p>Depois</p><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{edit.after}</pre></div>)}</details>}{j.review && <p>Sentinel: {j.review.approved ? 'aprovou a revisão textual' : 'rejeitou'} · {j.review.reason}. Nenhum teste foi executado pelo modelo.</p>}{j.prUrl && <div className="aw-actions"><a className="aw-button aw-secondary" href={j.prUrl} target="_blank" rel="noreferrer">Revisar PR no GitHub</a><button className="aw-button aw-secondary" disabled={busy} onClick={() => void mutate(() => agentApi.checkImprovement(j.id), 'Estado dos testes consultado para a versão exata da proposta.')}>Consultar testes CI</button></div>}{j.checks && <p>{checks[j.checks.status] || j.checks.status} · {j.checks.note}</p>}<details><summary>Abrir a branch no seu Codespaces</summary><p>No terminal do Codespaces, com o trabalho atual salvo:</p><pre style={{ overflowWrap: 'anywhere', whiteSpace: 'pre-wrap' }}>git fetch origin{ '\n' }git switch {j.branch}</pre><p>Revise o diff e o resultado do Agent checks antes de decidir integrar. A aplicação não executa esses comandos nem faz merge.</p></details>{j.status === 'uncertain' && <><a className="aw-button aw-secondary" href={`https://github.com/greenspyder/HubLoan/tree/${j.branch}`} target="_blank" rel="noreferrer">Conferir branch no GitHub</a><label className="aw-checkbox"><input type="checkbox" checked={checked[j.id] || false} onChange={e => setChecked(s => ({ ...s, [j.id]: e.target.checked }))} /> Conferi a branch e eventual PR e quero encerrar esta tentativa sem reenviá-la</label><button className="aw-button aw-secondary" disabled={busy || !checked[j.id]} onClick={() => void mutate(() => agentApi.acknowledgeImprovement(j.id, checked[j.id]), 'Tentativa encerrada sem reenvio. Renove os limites para outras melhorias.')}>Encerrar tentativa</button></>}{j.error && <p className="aw-error">{j.error}</p>}</article>)}
  </section>;
}
