import { useState } from 'react';
import { agentApi, type Workspace } from '../services/agentApi';
type Props={workspace:Workspace;busy:boolean;mutate:(op:()=>Promise<Workspace>,message?:string)=>Promise<Workspace|null>};
export function EtsyConnection({workspace:w,busy,mutate}:Props){const [error,setError]=useState(''),[url,setUrl]=useState('');const c=w.etsy;
 return <section className="aw-panel" id="etsy"><h2>Etsy · API oficial</h2><p>{c?.connected?`Conectada: ${c.shopName} · ${c.currency}`:'Configuração e autorização necessárias'}</p><ol><li>Crie/ative sua loja Etsy e uma aplicação aprovada para acesso à sua loja em <a href="https://www.etsy.com/developers/your-apps" target="_blank" rel="noreferrer">Your Apps</a>.</li><li>Registre o callback HTTPS do servidor: <code>{c?.redirectUri||'https://hubloan.onrender.com/api/agents/etsy/callback'}</code>.</li><li>Informe keystring, shared secret e ID da sua loja abaixo.</li><li>Autorize a conta proprietária da loja. Depois atualize esta tela.</li></ol><p>Escopos: shops_r, listings_r, listings_w, transactions_r. Credenciais são criptografadas no servidor. A publicação exige revisão e sua autorização para cada oferta.</p>
 <form className="aw-form" onSubmit={ev=>{ev.preventDefault();const form=ev.currentTarget,d=new FormData(form);void mutate(()=>agentApi.configureEtsy({clientId:String(d.get('clientId')),sharedSecret:String(d.get('sharedSecret')),shopId:Number(d.get('shopId'))}),'Aplicação Etsy configurada. Agora autorize a loja.').then(ok=>{if(ok)form.reset();});}}><label>API keystring<input name="clientId" autoComplete="off" required maxLength={200}/></label><label>Shared secret<input name="sharedSecret" type="password" autoComplete="new-password" required maxLength={200}/></label><label>ID da loja<input name="shopId" type="number" min={1} required defaultValue={c?.shopId}/></label><button disabled={busy} className="aw-button">Salvar configuração</button></form>
 {c?.configured&&!c.connected&&<button className="aw-button" disabled={busy} onClick={()=>{setError('');void agentApi.authorizeEtsy().then(r=>setUrl(r.url)).catch(e=>setError(e.message));}}>Preparar autorização Etsy</button>}{url&&<a className="aw-button" href={url} target="_blank" rel="noreferrer">Autorizar HubLoan na Etsy</a>}{c?.configured&&<button className="aw-button aw-secondary" disabled={busy} onClick={()=>void mutate(()=>agentApi.disconnectEtsy(),'Conexão Etsy removida deste espaço.')}>Remover conexão</button>}<p role="status">{error||c?.error}</p></section>;
}
export function EtsyPublication({experimentId,workspace:w,busy,mutate}:Props&{experimentId:string}){const e=w.experiments?.find(e=>e.id===experimentId),p=e?.marketplace?.etsy;if(!e)return null;
 return <section className="sc-summary"><h3>Etsy · publicação pela API</h3>{!w.etsy?.connected?<p><a href="/agentes/conexoes#etsy">Configure e autorize Etsy</a> para publicar pela API. A publicação manual continua disponível.</p>:<><p>Loja: {w.etsy.shopName} · moeda: {w.etsy.currency}. Preço em reais do teste não é convertido automaticamente.</p>{p?<><p>Envio: {p.status} · Listing: {p.listingId||'ID ainda não confirmado'}</p><p>{p.error}</p>{p.status!=='active'&&<form className="aw-form" onSubmit={ev=>{ev.preventDefault();const d=new FormData(ev.currentTarget);void mutate(()=>agentApi.etsyAction(e.id,'reconcile',{listingId:Number(d.get('listingId'))}),'Estado consultado na API. Nenhuma criação ou upload repetido.');}}><label>ID do listing encontrado na sua loja (se faltou confirmação)<input name="listingId" type="number" min={1} defaultValue={p.listingId}/></label><button disabled={busy} className="aw-button">Conferir listing existente</button></form>}</>:<form className="aw-form" onSubmit={ev=>{ev.preventDefault();const d=new FormData(ev.currentTarget);void mutate(()=>agentApi.etsyAction(e.id,'publish',{taxonomyId:Number(d.get('taxonomyId')),priceMinor:Math.round(Number(d.get('price'))*100),authorize:d.get('authorize')==='on',eligible:d.get('eligible')==='on'}),'Listing ativo confirmado pela API Etsy. Nenhuma venda presumida.');}}><label>ID da categoria Etsy (taxonomia oficial)<input name="taxonomyId" type="number" min={1} required/></label><a href="https://developers.etsy.com/documentation/reference/#operation/getSellerTaxonomyNodes" target="_blank" rel="noreferrer">Consultar categorias oficiais</a><label>Preço na moeda da loja ({w.etsy.currency})<input name="price" type="number" step="0.01" min="0.01" required/></label><label className="aw-checkbox"><input name="eligible" type="checkbox" required/>Examinei a oferta e os arquivos: criação própria elegível na Etsy, direitos suficientes e uso de IA declarado.</label><label className="aw-checkbox"><input name="authorize" type="checkbox" required/>Autorizar criar listing, enviar imagem/arquivo e publicar esta versão. A Etsy pode cobrar taxas de publicação; renovação automática ficará desligada.</label><button className="aw-button" disabled={busy||!e.originalityCurrent||!e.validationReadiness?.qualityCurrent}>Publicar versão revisada pela API</button></form>}{e.marketplace?.publication&&<button className="aw-button aw-secondary" disabled={busy} onClick={()=>void mutate(()=>agentApi.etsyAction(e.id,'sync'),'Pedidos consultados na Etsy. Revise taxas e demais custos para apurar resultado.')}>Sincronizar pedidos deste listing</button>}{e.marketplace?.apiSync&&<p>{e.marketplace.apiSync.note} · Pedidos correspondentes: {e.marketplace.apiSync.matchedReceipts} · Pendentes de conciliação: {e.marketplace.apiSync.unresolved}</p>}</>}</section>;
}
