import { MarketplaceOffer } from './MarketplaceOffer';
import { FirstSaleValidation } from './FirstSaleValidation';
import { useState } from 'react';
import { agentApi, type BusinessExperiment, type Workspace } from '../services/agentApi';
type Props = { workspace: Workspace; busy: boolean; mutate: (operation: () => Promise<Workspace>, success?: string) => Promise<Workspace | null> };
const money = (n: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(n / 100);
function minor(value: FormDataEntryValue | null) { const s = String(value || '').trim(); if (!/^\d{1,6}(?:[.,]\d{1,2})?$/.test(s)) throw new Error('Informe reais com até duas casas decimais.'); const [whole, fraction = ''] = s.split(/[.,]/); return Number(whole) * 100 + Number(fraction.padEnd(2, '0')); }
const categoryLabels: Record<string, string> = { api: 'API / IA', fees: 'Taxas de pagamento', taxes: 'Impostos', ads: 'Divulgação', labor: 'Trabalho', hosting: 'Hospedagem', other: 'Outros' };
const recommendations: Record<string, string> = { budget: 'Orçamento registrado atingido: interrompa novos gastos e revise', incomplete: 'Complete ou atualize os custos antes de avaliar o resultado', validated: 'Critério atingido neste teste: avalie repetir em pequena escala', stop: 'Prazo encerrado sem atingir o critério: pare ou reformule', observe: 'Dentro do prazo: continue observando sem aumentar o orçamento' };
export function ExperimentCard({ experiment: e, workspace, busy, mutate, financialOnly = false }: Props & { experiment: BusinessExperiment; financialOnly?: boolean }) {
  const [complete, setComplete] = useState(false);
  const [error, setError] = useState('');
  const m = e.marketplaceMetrics ? {...e.metrics,...e.marketplaceMetrics,balanceMinor:e.marketplaceMetrics.grossMinor-e.marketplaceMetrics.refundedMinor-e.metrics.costMinor} : e.metrics;
  const available = workspace.missions.filter(m => m.purpose !== 'experiment-preparation' && !workspace.experiments?.some(e => e.missionIds.includes(m.id)));
  async function cost(event: React.SubmitEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { const amountMinor = minor(data.get('amount')); const result = await mutate(() => agentApi.experimentAction(e.id, 'cost', { amountMinor, category: data.get('category'), note: data.get('note') }), 'Custo registrado. Revise os totais antes de avaliar o resultado.'); if (result) { form.reset(); setComplete(false); setError(''); } } catch (error) { setError(error instanceof Error ? error.message : 'Valor inválido.'); } }
  return <article className="aw-experiment" id={`experiment-${e.id}`}><div className="aw-section-title"><div><h3>{e.name}</h3><p className="aw-caption">{e.audience} · {e.channel}</p></div><span className="aw-badge">{e.ended ? 'TESTE ENCERRADO' : 'EM OBSERVAÇÃO'}</span></div><p>{e.hypothesis}</p><p className="aw-caption">Janela: {new Date(e.createdAt).toLocaleDateString('pt-BR')} até {new Date(e.closedAt || e.endsAt).toLocaleString('pt-BR')}. Critério: {e.minSales} venda(s) retida(s) e resultado de pelo menos {money(e.minNetMinor)}, com custos revisados.</p>
    {!financialOnly && <><FirstSaleValidation experiment={e} workspace={workspace} busy={busy} mutate={mutate} /><MarketplaceOffer experiment={e} workspace={workspace} busy={busy} mutate={mutate} /></>}<div className="aw-experiment-metrics"><div><small>{(e.salesChannel || e.marketplace) ? 'Vendas externas declaradas' : 'Vendas reais retidas'}</small><strong>{(e.salesChannel || e.marketplace) && !e.marketplaceMetrics ? "Não informado" : m.sales}</strong></div><div><small>{(e.salesChannel || e.marketplace) ? 'Receita externa declarada' : 'Receita bruta Stripe'}</small><strong>{(e.salesChannel || e.marketplace) && !e.marketplaceMetrics ? "Não informada" : money(m.grossMinor)}</strong></div><div><small>Custos declarados</small><strong>{money(m.costMinor)}</strong></div><div><small>{m.costComplete ? 'Resultado com custos declarados' : 'Resultado ainda incompleto'}</small><strong>{(e.salesChannel || e.marketplace) && !e.marketplaceMetrics || m.resultMinor === null ? 'A apurar' : money(m.resultMinor)}</strong></div></div>
    <p className="aw-caption">Reembolsos: {money(m.refundedMinor)} · Valores contestados/retidos: {money(m.heldMinor)} · Saldo parcial conhecido: {money(m.balanceMinor)}.</p><progress max={e.budgetMinor} value={Math.min(e.budgetMinor, m.costMinor)} aria-label={`Custos registrados ${money(m.costMinor)} de orçamento ${money(e.budgetMinor)}`} /><p className="aw-caption">Orçamento: {money(e.budgetMinor)} · {m.budgetRemainingMinor < 0 ? 'Excedido em' : 'Restante registrado'} {money(Math.abs(m.budgetRemainingMinor))}. Não é bloqueio de cobrança da API.</p><p className="aw-experiment-verdict">{(e.salesChannel || e.marketplace) ? !e.marketplaceMetrics || !m.costComplete ? "A apurar: registre resultados externos e revise custos." : m.resultMinor!==null && m.resultMinor>0 && m.sales>=e.minSales && m.resultMinor>=e.minNetMinor ? "Critério atingido conforme seu relato; revise evidências e considere outro teste pequeno." : e.ended ? "Teste encerrado: avalie parar ou reformular; confira distribuição e dados." : "Continue observando sem aumentar o orçamento." : recommendations[m.recommendation]}</p>
    <details><summary>Entregas e pagamentos atribuídos</summary><p className="aw-caption">Na loja própria, pagamentos Stripe confirmados são atribuídos por entrega e janela. Em uma oferta externa, somente os totais declarados daquele marketplace entram no resultado: vendas Stripe ficam fora deste teste. Informe reembolsos e correções para atualizar os resultados.</p>{e.missionIds.length ? <ul>{e.missionIds.map(id => <li key={id}>{workspace.missions.find(m => m.id === id)?.title || 'Entrega indisponível'}</li>)}</ul> : <p>Sem entrega vinculada: este experimento ainda é um plano.</p>}{!e.ended && available.length > 0 && <form className="aw-form" onSubmit={event => { event.preventDefault(); const id = String(new FormData(event.currentTarget).get('mission')); void mutate(() => agentApi.experimentAction(e.id, 'link', { missionId: id }), 'Entrega vinculada ao teste.'); }}><label>Adicionar entrega<select name="mission">{available.map(m => <option key={m.id} value={m.id}>{m.title}</option>)}</select></label><button className="aw-button aw-secondary" disabled={busy}>Vincular entrega</button></form>}<p className="aw-caption">Cada entrega pertence a um único experimento para evitar contar uma venda duas vezes. Vincular não publica nem inicia a produção.</p></details>
    <details open={financialOnly}><summary>Registrar taxas, outros custos e conferir o resultado</summary><p className="aw-caption">Informe despesas em reais efetivamente atribuídas a este teste. Não registre a recarga inteira da API como consumo se parte do saldo ainda não foi usada. Rateie custos compartilhados e registre o critério na descrição. Custos não são obtidos automaticamente dos provedores.</p><form className="aw-form" onSubmit={cost}><div className="aw-columns"><label>Categoria<select name="category">{Object.entries(categoryLabels).map(([value, name]) => <option key={value} value={value}>{name}</option>)}</select></label><label>Valor em R$<input name="amount" inputMode="decimal" placeholder="Ex.: 3,50" required /></label></div><label>Descrição / referência<input name="note" maxLength={300} required placeholder="Ex.: consumo da API do teste, conforme painel do provedor" /></label><button className="aw-button" disabled={busy}>Registrar custo</button></form>{error && <p role="alert">{error}</p>}
      <ul className="aw-cost-list">{e.costs.map(c => <li key={c.id}><span>{categoryLabels[c.category]} · {c.note}<small>{money(c.amountMinor)} · {c.voidedAt ? 'Estornado' : 'Informado por você'}</small></span>{!c.voidedAt && <button className="aw-button aw-secondary" disabled={busy} onClick={() => void mutate(() => agentApi.experimentAction(e.id, 'void', { costId: c.id }), 'Lançamento estornado; histórico preservado.')}>Estornar</button>}</li>)}</ul>
      <label className="aw-checkbox"><input type="checkbox" checked={complete} onChange={event => setComplete(event.target.checked)} /> Revisei API, taxas, impostos, divulgação, trabalho, hospedagem e outros, inclusive valores zero. Os custos registrados cobrem este experimento.</label><button className="aw-button aw-secondary" disabled={busy || !complete} onClick={() => void mutate(() => agentApi.experimentAction(e.id, 'review', { complete: true }), 'Custos revisados. Novas vendas ou alterações na produção exigem nova revisão.').then(result => { if (result) setComplete(false); })}>Confirmar revisão dos custos</button><p className="aw-caption">O resultado depende da exatidão dos custos informados; não é uma apuração contábil. Nova atividade, venda, reembolso ou custo invalida a revisão anterior.</p>
    </details>{!e.ended && <button className="aw-button aw-secondary" disabled={busy} onClick={() => void mutate(() => agentApi.experimentAction(e.id, 'close'), 'Janela do teste encerrada. Isso não pausa projetos ou anúncios.')}>Encerrar janela do teste</button>}
  </article>;
}
export function ExperimentsPanel(props: Props) {
  const { workspace, busy, mutate } = props;
  const [error, setError] = useState('');
  const experiments = workspace.experiments;
  const available = workspace.missions.filter(m => m.purpose !== 'experiment-preparation' && !experiments?.some(e => e.missionIds.includes(m.id)));
  async function create(event: React.SubmitEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const d = new FormData(form); try { const input = { name: String(d.get('name')), hypothesis: String(d.get('hypothesis')), audience: String(d.get('audience')), channel: String(d.get('channel')), budgetMinor: minor(d.get('budget')), days: Number(d.get('days')), minSales: Number(d.get('sales')), minNetMinor: minor(d.get('net')), missionIds: d.getAll('missions').map(String) }; const result = await mutate(() => agentApi.addExperiment(input), 'Experimento salvo sem executar IA ou publicar ofertas.'); if (result) { form.reset(); setError(''); } } catch (error) { setError(error instanceof Error ? error.message : 'Valores inválidos.'); } }
  return <section className="aw-panel" id="experiments"><div className="aw-section-title"><div><p className="aw-eyebrow">HIPÓTESE / ORÇAMENTO / RESULTADO</p><h2>Experimentos e resultado financeiro</h2></div><span className="aw-badge">{experiments?.length || 0} TESTES</span></div><p className="aw-caption">Teste pequeno antes de escalar: defina quem compraria, a oferta, um prazo e um critério verificável. Receita confirmada menos reembolsos e custos declarados forma o resultado deste teste. Sem custos completos, o painel mostra saldo parcial.</p><div className="aw-notice"><p>O orçamento acompanha despesas registradas; não impede novas cobranças. Os limites de chamadas da Autonomia continuam valendo. Encerrar um teste não pausa produção, anúncios ou vendas: use os controles dessas integrações para interrompê-los.</p></div>
    {experiments === undefined ? <p>Aguardando atualização do backend para habilitar este painel.</p> : <><details open={!experiments.length}><summary>Planejar um experimento sem gastar API</summary><form className="aw-form" onSubmit={create}><label>Nome do teste<input name="name" maxLength={100} required placeholder="Ex.: template de planejamento para freelancers" /></label><label>Hipótese da oferta<textarea name="hypothesis" maxLength={1000} required placeholder="Acredito que este público pagaria por este produto porque…" /></label><div className="aw-columns"><label>Público<input name="audience" maxLength={300} required /></label><label>Canal de teste<input name="channel" maxLength={200} required placeholder="Ex.: Fiverr — thumbnails para creators" /></label></div><div className="aw-columns"><label>Orçamento em R$<input name="budget" inputMode="decimal" defaultValue="60,00" required /></label><label>Prazo em dias<input name="days" type="number" min={1} max={90} defaultValue={7} required /></label><label>Mínimo de vendas retidas<input name="sales" type="number" min={1} max={10000} defaultValue={1} required /></label><label>Resultado mínimo em R$<input name="net" inputMode="decimal" defaultValue="10,00" required /></label></div>{available.length > 0 && <fieldset className="aw-experiment-deliveries"><legend>Entregas opcionais; podem ser vinculadas depois</legend>{available.map(m => <label className="aw-checkbox" key={m.id}><input type="checkbox" name="missions" value={m.id} /> {m.title}</label>)}</fieldset>}<button className="aw-button" disabled={busy}>Salvar plano de experimento</button>{error && <p role="alert">{error}</p>}</form></details>{!experiments.length && <p className="aw-caption">Nenhum teste registrado. Salvar um plano não consome API, publica ofertas ou inventa compradores.</p>}{experiments.map(e => <ExperimentCard key={e.id} {...props} experiment={e} />)}</>}
  </section>;
}
