import { useState } from 'react';
import { addFactory, agentApi, productionLabels, type Factory, type ProductionKind, type Workspace } from '../services/agentApi';
import { RobotSprite } from './RobotSprite';
const kinds = { ...productionLabels, video: 'Vídeos de nicho · integração pendente', service: 'Serviços · integração pendente', software: 'Software publicado · integração pendente' };
const money = (n: number) => (n / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
type Props = { workspace: Workspace; busy: boolean; mutate: (op: () => Promise<Workspace>, success?: string) => Promise<Workspace | null> };
export function FactoriesPanel({ workspace, busy, mutate }: Props) {
  const [selected, setSelected] = useState('');
  const [creating, setCreating] = useState(false);
  const [draft, setDraft] = useState<Pick<Factory, 'name' | 'kind' | 'role' | 'audience' | 'channel'>>({ name: '', kind: 'text', role: '', audience: '', channel: '' });
  const [goal, setGoal] = useState('');
  const factories = workspace.factories || [];
  const current = factories.find(f => f.id === selected) || factories[0];
  const missions = current ? workspace.missions.filter(m => m.factoryId === current.id) : [];
  const suggestions = (workspace.autonomy?.projects || []).flatMap(p => (p.decisions || []).flatMap(d => d.candidates)).filter(c => c.businessModel && c.execution?.status !== 'executable').slice(0, 5);
  return <section className="aw-panel" id="factories"><div className="aw-section-title"><div><p className="aw-eyebrow">UNIDADES DE NEGÓCIO / PRODUÇÃO REAL</p><h2>Suas fábricas</h2></div><span className="aw-badge">{factories.length} UNIDADES</span></div>
    <p>Cada fábrica tem uma especialidade, público e responsabilidade que orientam a produção e a revisão. Astra distribui descobertas pelos formatos disponíveis. Os agentes e os limites de IA são compartilhados, com um projeto autônomo ativo por vez; uma fábrica cadastrada não inicia gastos.</p>
    <div className="aw-factory-hub"><strong>ASTRA · ORQUESTRADOR</strong><span>Pesquisa → escolha da oportunidade → fábrica especializada → revisão → canais autorizados</span></div>
    <div className="aw-factory-grid" aria-label="Selecionar fábrica">{factories.map((f, index) => <button key={f.id} className={`aw-factory-building ${f.running ? 'is-working' : ''}`} aria-pressed={current?.id === f.id} onClick={() => { setSelected(f.id); setGoal(''); }}><span className="aw-factory-roof" aria-hidden="true">▥ ▥ ▥</span><span className="aw-factory-worker" aria-hidden="true"><RobotSprite commander={false} role={index % 2 ? 'creator' : 'research'} delivery={false} /></span><strong>{f.name}</strong><span>{f.blocker ? 'Integração pendente' : f.running ? `${f.running} em produção` : f.queued ? `${f.queued} na fila` : 'Em espera'}</span><small>{f.delivered} entregas · {f.projects} projetos vinculados</small></button>)}</div>
    {!factories.length && <p>Aguardando o servidor carregar as fábricas.</p>}
    {current && <article className="aw-factory-detail"><h3>{current.name}</h3><p>{current.role}</p><p><strong>Público:</strong> {current.audience}<br /><strong>Canal pretendido:</strong> {current.channel}</p><p className="aw-caption">O canal é contexto comercial. A publicação segue as conexões e autorizações da loja e do itch.io; escrever um canal aqui não o conecta.</p>
      <div className="aw-experiment-metrics"><div><small>Entregas produzidas</small><strong>{current.delivered}</strong></div><div><small>Reservas de API</small><strong>{money(current.reservedMinor)}</strong></div><div><small>Receita de testes exclusivos</small><strong>{money(current.grossMinor)}</strong></div><div><small>Resultado com custos declarados</small><strong>{current.resultMinor === null ? 'A apurar' : money(current.resultMinor)}</strong></div></div>
      <p className="aw-caption">Custos declarados nos testes exclusivos: {money(current.costMinor)}. Reservas de API não são despesas faturadas. Resultados incluem somente experimentos cujas entregas pertencem integralmente a esta fábrica; {current.mixedExperiments} teste(s) com fábricas misturadas ou entregas repetidas entre experimentos ficam fora. Coordenação da descoberta ampla não é rateada automaticamente.</p><a href="#experiments">Vincular entregas a experimentos e revisar custos →</a>
      {current.blocker ? <p className="aw-notice">{current.blocker} Esta unidade registra o plano de negócio; criar a fábrica não implementa essas ferramentas.</p> : <form className="aw-form" onSubmit={e => { e.preventDefault(); void mutate(() => agentApi.addProject({ factoryId: current.id, name: `Teste · ${current.name}`, mode: 'goal', kind: current.kind as ProductionKind, goal, maxDeliveries: 1, intervalMinutes: 5, maxCalls: 15, research: false, start: false }), 'Projeto da fábrica salvo e pausado. Revise os limites e inicie em Autonomia.').then(w => { if (w) setGoal(''); }); }}><label>Objetivo do próximo teste<textarea value={goal} onChange={e => setGoal(e.target.value)} maxLength={2500} required placeholder="Descreva uma única entrega original, seu público e critérios de qualidade." /></label><button className="aw-button" disabled={busy}>Preparar projeto desta fábrica</button><small>Cria um projeto pausado, com uma entrega e até 15 chamadas. Para executar, confira o orçamento e autorize em Autonomia. Imagens podem gerar cobranças adicionais.</small></form>}
      <details><summary>Tarefas desta fábrica ({missions.length})</summary>{missions.length ? missions.map(m => <p key={m.id}><strong>{m.title}</strong> · {m.phase}</p>) : <p>Nenhuma tarefa atribuída.</p>}</details></article>}
    <details open={creating} onToggle={e => setCreating(e.currentTarget.open)}><summary>Criar uma nova fábrica</summary><p>Defina uma atividade específica, como thumbnails de culinária ou mobília 3D para jogos. A especialidade determina o pipeline real. Novas fontes de renda podem ser planejadas mesmo quando ainda faltam integrações.</p><form className="aw-form" onSubmit={e => { e.preventDefault(); void mutate(() => addFactory(draft), 'Fábrica cadastrada; nenhuma execução iniciada.').then(w => { if (w) { setSelected(w.factories?.at(-1)?.id || ''); setCreating(false); setDraft({ name: '', kind: 'text', role: '', audience: '', channel: '' }); } }); }}><label>Nome da fábrica<input value={draft.name} maxLength={80} required onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label>Especialidade<select value={draft.kind} onChange={e => setDraft({ ...draft, kind: e.target.value as Factory['kind'] })}>{Object.entries(kinds).map(([k, label]) => <option key={k} value={k}>{label}</option>)}</select></label><label>Responsabilidade e critérios de qualidade<textarea value={draft.role} maxLength={1000} required onChange={e => setDraft({ ...draft, role: e.target.value })} /></label><label>Público<input value={draft.audience} maxLength={300} required onChange={e => setDraft({ ...draft, audience: e.target.value })} /></label><label>Canal de receita pretendido<input value={draft.channel} maxLength={200} required onChange={e => setDraft({ ...draft, channel: e.target.value })} /></label><button className="aw-button" disabled={busy || factories.length >= 20}>Cadastrar fábrica</button></form></details>
    <details><summary>Oportunidades para futuras fábricas</summary>{suggestions.length ? suggestions.map((c, i) => <article key={`${c.id}-${i}`}><h3>{c.title}</h3><p>{c.monetization}</p><p>{c.execution?.missing.map(m => m.reason).join(' ')}</p><button className="aw-button aw-secondary" onClick={() => { setCreating(true); setDraft({ name: c.title.slice(0, 80), kind: c.businessModel === 'content_channel' ? 'video' : c.businessModel === 'service' ? 'service' : c.businessModel === 'software' ? 'software' : c.kind, role: c.test, audience: c.audience, channel: c.platform || 'A definir' }); }}>Preencher cadastro com esta hipótese</button></article>) : <p>Oportunidades pesquisadas com etapas pendentes aparecerão aqui. Sem pesquisa registrada, nenhuma oportunidade é presumida.</p>}</details>
  </section>;
}
