import { useState } from 'react';
import { agentApi, productionLabels, type BusinessExperiment, type Workspace } from '../services/agentApi';
type Props={stage?:'prepare'|'review'|'results';experiment:BusinessExperiment;workspace:Workspace;busy:boolean;mutate:(operation:()=>Promise<Workspace>,success?:string)=>Promise<Workspace|null>};
type Action=Parameters<typeof agentApi.experimentAction>[1];
export function FirstSaleValidation({experiment:e,workspace,busy,mutate,stage}:Props){
 const [error,setError]=useState('');const v=e.validation,r=e.validationReadiness;
 const mission=workspace.missions.find(m=>m.id===v?.sampleId);
 const assignedFactory=workspace.factories?.find(f=>f.id===(e.salesChannel || e.marketplace)?.factoryId);
 const external=Boolean(e.salesChannel || e.marketplace);
 async function submit(event:React.SubmitEvent<HTMLFormElement>,action:Action,parse:(d:FormData)=>object){event.preventDefault();const form=event.currentTarget;try{setError('');const input=parse(new FormData(form));const result=await mutate(()=>agentApi.experimentAction(e.id,action,input),'Etapa de validação registrada.');if(result&&action==='validation-feedback')form.reset();}catch(err){setError(err instanceof Error?err.message:'Confira os campos.');}}
 if(!v)return <div className="aw-notice"><div><strong>Modo primeira venda</strong><p>Uma amostra por teste, revisão humana e liberação explícita antes da publicação na loja própria. Interesse declarado não conta como venda. Ative em um plano aberto sem entregas.</p><button className="aw-button aw-secondary" disabled={busy||e.ended||e.missionIds.length>0} onClick={()=>void mutate(()=>agentApi.experimentAction(e.id,'validation-enable'),'Modo primeira venda ativado; nenhuma produção iniciada.')}>Ativar validação antes de produzir</button></div></div>;
 return <div className="aw-first-sale"><h3>Primeira venda · o que falta comprovar</h3><p className="aw-caption">Valide uma oferta pequena. Use o kit abaixo para Fiverr/Etsy manualmente ou a liberação para a loja própria. Atendimento de pedidos externos permanece manual. Orçamento declarado não bloqueia cobranças; salvar as etapas abaixo não executa IA.</p>
 {!stage && <><ul className="aw-validation-checks">{r?.checks.map(c=><li key={c.id}><span aria-hidden="true">{c.met?'✓':'○'}</span><span>{c.met?'Registrado: ':'Pendente: '}{c.label}</span></li>)}</ul>
 <p className="aw-experiment-verdict">{r?.canConsiderRepeating?'Há resultado positivo registrado com custos declarados e amostra revisada. Confira a origem dos pagamentos antes de repetir. Avalie um novo teste pequeno; não há aumento automático.':'Ainda não há evidência suficiente para recomendar repetir ou escalar.'}</p></>}
 {(!stage || stage==='prepare') && <><details open={!v.evidence}><summary>1. Registrar um pedido ou problema real</summary><p className="aw-caption">Copie uma fonte pública e descreva o que foi observado. O registro é seu relato, sem verificação independente. Evite nomes, contatos e informações pessoais.</p>{v.evidence&&<p className="aw-caption"><a href={v.evidence.url} target="_blank" rel="noreferrer">Ver fonte registrada</a> · {v.evidence.summary}</p>}
 {!v.sampleId&&<form className="aw-form" onSubmit={ev=>void submit(ev,'validation-evidence',d=>({url:d.get('url'),summary:d.get('summary'),observedAt:d.get('observedAt')}))}><label>URL pública<input name="url" type="url" required maxLength={1500} defaultValue={v.evidence?.url}/></label><label>Pedido ou problema observado<textarea name="summary" required maxLength={1000} defaultValue={v.evidence?.summary}/></label><label>Data da consulta (últimos 30 dias)<input name="observedAt" type="date" required defaultValue={v.evidence?.observedAt.slice(0,10)||new Date().toISOString().slice(0,10)}/></label><button className="aw-button aw-secondary" disabled={busy||e.ended}>Salvar evidência</button></form>}</details>
 <details open={Boolean(v.evidence&&!v.offer)}><summary>2. Definir uma oferta pequena</summary>{v.offer&&<p className="aw-caption">{v.offer.scope} · Preço proposto R$ {(v.offer.priceMinor/100).toFixed(2)} · Prazo {v.offer.deliveryDays} dias. Critérios: {v.offer.criteria}</p>}
 {!v.sampleId&&<form className="aw-form" onSubmit={ev=>void submit(ev,'validation-offer',d=>({scope:d.get('scope'),criteria:d.get('criteria'),priceMinor:Math.round(Number(String(d.get('price')).replace(',','.'))*100),deliveryDays:Number(d.get('days'))}))}><label>Escopo e entregáveis<textarea name="scope" required maxLength={1000} defaultValue={v.offer?.scope}/></label><div className="aw-columns"><label>Preço proposto (R$)<input name="price" type="number" min="5" max="10000" step="0.01" required defaultValue={v.offer?v.offer.priceMinor/100:undefined}/></label><label>Prazo proposto (dias)<input name="days" type="number" min="1" max="90" required defaultValue={v.offer?.deliveryDays||3}/></label></div><label>Critérios de qualidade<textarea name="criteria" required maxLength={800} placeholder="Ex.: texto legível no celular, tamanho correto e conteúdo original." defaultValue={v.offer?.criteria}/></label><button className="aw-button aw-secondary" disabled={busy||e.ended}>Salvar oferta</button></form>}</details>
 <details open={Boolean(v.offer&&!v.sampleId)}><summary>3. Preparar uma única amostra</summary>{mission?<p className="aw-caption">{mission.title} · {mission.phase}. <a href={`/agentes/armazem?mission=${mission.id}#terminal`}>Examinar amostra e baixar arquivos</a>. A execução usa sua chave e gera custos. {mission.status==='draft' && <button className="aw-button" disabled={busy || !workspace.settings.configured} onClick={()=>void mutate(()=>agentApi.action(mission.id,'run'),'Amostra enfileirada; acompanhe no Armazém.')}>Executar amostra com IA (pago)</button>}</p>:<form className="aw-form" onSubmit={ev=>void submit(ev,'validation-sample',d=>({kind:assignedFactory?.kind || d.get('kind'),agentId:d.get('agentId'),allowImages:d.get('allowImages')==='on'}))}><label>Formato<select name="kind" defaultValue={assignedFactory?.kind || 'text'} disabled={Boolean(assignedFactory)}>{Object.entries(productionLabels).map(([k,label])=><option key={k} value={k}>{label}</option>)}</select></label><label>Responsável<select name="agentId">{workspace.agents.filter(a=>a.enabled).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="aw-checkbox"><input name="allowImages" type="checkbox"/>Autorizo formato de imagem, caso selecionado; executar depois terá cobrança adicional.</label><button className="aw-button aw-secondary" disabled={busy||e.ended||!v.evidence||!v.offer}>Criar rascunho da amostra</button></form>}</details>
 </>}
 {(!stage || stage==='review') && <details open={stage==='review'}><summary>4. Revisar a qualidade e liberar a oferta</summary><p className="aw-caption">Baixe e examine a entrega em Missões. Sua revisão vale para esta versão; alterar ou refazer a entrega invalida a liberação. Para loja própria, aprove a entrega no Armazém e autorize a oferta individual na Loja pelo mesmo preço proposto. Para marketplaces, use o kit manual abaixo.</p>{v.quality&&<p className="aw-caption">Avaliação registrada: {v.quality.approved?'aprovada':'reprovada'} · {v.quality.reason}</p>}
 <form className="aw-form" onSubmit={ev=>void submit(ev,'validation-quality',d=>({approved:d.get('approved')==='yes',reason:d.get('reason')}))}><label>Resultado da sua revisão<select name="approved" required defaultValue=""><option value="" disabled>Selecione após examinar</option><option value="yes">Amostra atende aos critérios</option><option value="no">Amostra precisa de correção</option></select></label><label>O que foi conferido?<textarea name="reason" required maxLength={800}/></label><button className="aw-button aw-secondary" disabled={busy||e.ended||!mission||!['review','approved'].includes(mission.status)}>Registrar revisão humana</button></form>
 {!external&&<form className="aw-form" onSubmit={ev=>void submit(ev,'validation-release',d=>({authorize:d.get('authorize')==='on'}))}><label className="aw-checkbox"><input name="authorize" type="checkbox" required/>Libero a versão revisada para publicação na loja própria, pelo preço proposto, conforme as integrações já autorizadas.</label><button className="aw-button" disabled={busy||e.ended||!r?.qualityCurrent}>Liberar oferta revisada</button></form>}<p className="aw-caption">{external ? 'Para publicar no marketplace, use a etapa Publicar.' : r?.publicationAllowed?'Liberação registrada. A publicação depende da loja configurada e das suas autorizações.':'Publicação desta amostra bloqueada.'} Liberação não envia mensagens, gera compradores ou ativa integrações. Se já publicou, use os controles da loja para retirar uma oferta; encerrar o teste não remove produtos existentes.</p></details>}
 {(!stage || stage==='results') && <details><summary>5. Registrar interesse e aprender com rejeições</summary><p className="aw-caption">Registre somente respostas observadas. Silêncio não explica por que alguém não comprou. Estes relatos nunca aumentam o contador de vendas ou a receita.</p><form className="aw-form" onSubmit={ev=>void submit(ev,'validation-feedback',d=>({outcome:d.get('outcome'),reason:d.get('reason')}))}><label>Resposta observada<select name="outcome"><option value="interested">Demonstrou interesse (não é compra)</option><option value="rejected">Recusou ou relatou uma objeção</option><option value="no-response">Sem resposta; motivo desconhecido</option></select></label><label>Observação sem dados pessoais<textarea name="reason" required maxLength={500}/></label><button className="aw-button aw-secondary" disabled={busy}>Registrar relato</button></form><ul>{v.feedback.map((f,i)=><li key={i} className="aw-caption">{new Date(f.at).toLocaleString('pt-BR')} · {f.outcome==='interested'?'Interesse':f.outcome==='rejected'?'Rejeição':'Sem resposta'} · {f.reason} (relato do proprietário)</li>)}</ul></details>}
 {v.quality?.approved===false&&<p className="aw-caption">Amostra reprovada: registre os custos e o resultado, encerre este teste e planeje outro com as correções. Este fluxo ainda não edita entregas.</p>}<p className="aw-caption">6. Acompanhe pagamentos confirmados e registre todas as despesas nos controles financeiros deste experimento. {r?.note}</p>{error&&<p role="alert">{error}</p>}</div>;
}
