import { useState } from 'react';
import { Link } from 'react-router-dom';
import { agentApi, type Workspace } from '../services/agentApi';
import { offerUrl } from '../services/salesChannels';
type Props={workspace:Workspace;busy:boolean;mutate:(operation:()=>Promise<Workspace>,success?:string)=>Promise<Workspace|null>};
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);
export function FirstSaleProject({workspace:w,busy,mutate}:Props) {
 const [error,setError]=useState('');
 async function create(event:React.SubmitEvent<HTMLFormElement>) {
  event.preventDefault();setError('');const d=new FormData(event.currentTarget), raw=String(d.get('budget'));
  if(!/^\d+(?:[.,]\d{1,2})?$/.test(raw)){setError('Informe reais com até duas casas decimais.');return;}
  const budgetMinor=Math.round(Number(raw.replace(',','.'))*100), start=d.get('autonomy')==='research';
  await mutate(()=>agentApi.addProject({firstSale:true,name:'Primeira Venda Autônoma',goal:String(d.get('goal')),budgetMinor,mode:'discover',kind:'text',research:true,maxDeliveries:1,maxCalls:12,intervalMinutes:5,start,market:{scope:'products',allowImages:true,allowPreparation:false,specializations:['sprites','model3d','text'],market:'Compradores independentes de recursos para jogos; proprietário brasileiro sem MEI/CNPJ',channels:'itch.io prioritário; prontidão de pagamentos deve ser conferida separadamente. Não presumir Etsy/Fiverr operacionais.',restrictions:'Pesquisar e propor um experimento pequeno. Sem publicar, comprar, anúncios pagos ou produzir antes de aprovação. Comparar custo e distribuição; preço anunciado não comprova venda.'}}),'Projeto salvo. Pesquisa autorizada somente se selecionada; produção e publicação continuam exigindo seus próprios gates.');
 }
 return <section className="aw-panel" id="first-sale"><p className="aw-eyebrow">OBJETIVO ECONÔMICO</p><h2>Primeira Venda Autônoma</h2><p>Primeira venda → margem positiva → R$ 50/mês → R$ 100/mês. São metas experimentais; lucro e recorrência ainda precisam de evidência.</p>
 {w.autonomy.projects.filter(p=>p.firstSale).map(p=>{const s=p.commercialSummary,chosen=p.decisions?.at(-1)?.selected,existing=w.experiments?.find(e=>e.projectId===p.id);return <article className="aw-project" key={p.id}><h3>{p.name}</h3><p>{p.goal}</p><p><strong>Próxima ação: </strong>{s?.next.label || p.phase}</p>{s&&<><p>Teto de exposição aplicado: {s.budgetMinor==null?'não definido':money(s.budgetMinor)} · Disponível: {s.remainingMinor==null?'a apurar':money(s.remainingMinor)}</p><p>IA confirmada: {s.costs.hasConfirmedCosts?money(s.costs.confirmedMinor):'a apurar'} · Reserva em andamento: {money(s.costs.reservedMinor)} · Exposição incerta: {money(s.costs.unknownMinor)} · Outros lançamentos do teste: {money(s.costs.declaredMinor)}</p><p className="aw-caption">{s.note}</p><Link className="aw-button aw-secondary" to={s.next.href}>Resolver próxima etapa</Link></>}
 {chosen&&!existing&&<><h4>Hipótese da Astra: {chosen.title}</h4><p>{chosen.rationale}</p><p>Incerteza: {chosen.uncertainty}</p><p>Teste sugerido: {chosen.test}</p><p>Preparar um teste não autoriza produção nem publicação.</p>{w.factories?.filter(f=>f.kind===chosen.kind&&['sprites','model3d'].includes(f.kind)).map(f=><Link key={f.id} className="aw-button" to={`${offerUrl(f.id,'itchio')}&project=${p.id}`}>Preparar oferta com {f.name}</Link>)}{!['sprites','model3d'].includes(chosen.kind)&&<p>Este formato exige um fluxo de distribuição ainda não integrado ao itch.io. Revise a viabilidade antes de produzir.</p>}</>}
 </article>;})}
 <details open={!w.autonomy.projects.some(p=>p.firstSale)}><summary>Criar projeto de primeira venda</summary><form className="aw-form" onSubmit={event=>void create(event)}><label>O que deseja alcançar?<textarea name="goal" required maxLength={4000} defaultValue="Conseguir a primeira venda lucrativa de um recurso original para jogos no itch.io, com o menor experimento viável."/></label><label>Teto de exposição do projeto (R$)<input name="budget" required inputMode="decimal" placeholder="Ex.: 30,00"/></label><label>Autonomia<select name="autonomy" defaultValue="manual"><option value="manual">Salvar e iniciar depois</option><option value="research" disabled={!w.settings.configured||!w.autonomy.durable||w.autonomy.enabled}>Pesquisar e propor; pausar antes de produzir</option></select></label><p className="aw-caption">O servidor bloqueia novas chamadas quando a exposição estimada alcança o teto. Reservas usam os valores configurados; não são um limite de cobrança imposto ao provedor. Limites globais e do experimento também se aplicam. Nenhuma configuração de pagamento será alterada.</p><button className="aw-button" disabled={busy}>Criar projeto</button>{error&&<p role="alert">{error}</p>}</form></details></section>;
}
