import { useState } from 'react';
import { agentApi, type Workspace, type ItchChecks } from '../services/agentApi';
type Props={workspace:Workspace;busy:boolean;mutate:(operation:()=>Promise<Workspace>,success?:string)=>Promise<Workspace|null>};
const fields={seller:'Conta de vendedor configurada',taxInterview:'Entrevista fiscal concluída',taxApproval:'Aprovação fiscal',payoutDestination:'Destino dos repasses configurado',acceptsPayments:'Capacidade de aceitar pagamentos reais'};
export function ItchReadiness({workspace:w,busy,mutate}:Props){
 const r=w.commerce?.readiness;
 const [checks,setChecks]=useState<ItchChecks>(r?.checks||{seller:'unknown',taxInterview:'unknown',taxApproval:'unknown',payoutDestination:'unknown',acceptsPayments:'unknown'}),[note,setNote]=useState(r?.note||'');
 return <section aria-label="Prontidão comercial itch.io"><h3>Conectividade não comprova prontidão para vender</h3><p>{r?.nextAction||'Conferir configuração de pagamentos no itch.io'}</p><p>O Stripe da loja própria é independente. A API de catálogo não confirma situação fiscal, repasses nem a conclusão de um checkout.</p>{r?.checkedAt&&<p>Conferência informada por você: {new Date(r.checkedAt).toLocaleString('pt-BR')}{r.stale?' · desatualizada':''}. Não verificada pela API.</p>}<a className="aw-button aw-secondary" href="https://itch.io/dashboard" target="_blank" rel="noreferrer">Conferir painel itch.io</a><details><summary>Registrar o que conferi, sem alterar minha conta</summary><form className="aw-form" onSubmit={e=>{e.preventDefault();void mutate(()=>agentApi.recordItchReadiness({checks,note}),'Conferência registrada como relato do proprietário; nenhuma configuração fiscal ou de pagamentos foi alterada.');}}>{(Object.keys(fields) as (keyof ItchChecks)[]).map(k=><label key={k}>{fields[k]}<select value={checks[k]} onChange={e=>setChecks({...checks,[k]:e.target.value as ItchChecks[typeof k]})}><option value="unknown">Não conferido</option><option value="pending">Pendente</option><option value="confirmed">Conferido no painel</option>{!['seller','acceptsPayments'].includes(k)&&<option value="not_applicable">Não aplicável ao meu modo de recebimento</option>}</select></label>)}<label>O que o painel mostrou? Sem dados bancários ou fiscais pessoais<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={600} required/></label><button className="aw-button" disabled={busy}>Salvar conferência</button></form></details></section>;
}
