import { useState } from 'react';
import { agentApi, type Workspace } from '../services/agentApi';
export function KnowledgePanel({workspace,busy,mutate}:{workspace:Workspace;busy:boolean;mutate:(operation:()=>Promise<Workspace>,success?:string)=>Promise<Workspace|null>}) {
  const [key,setKey]=useState(''), [authorize,setAuthorize]=useState(false), [filter,setFilter]=useState(''), [error,setError]=useState('');
  const k=workspace.knowledge;
  async function exportNotes(){try{setError('');const result=await agentApi.exportKnowledge();const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='hubloan-memoria-private.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Falha ao exportar.');}}
  return <section className="aw-panel" id="knowledge"><header className="aw-section-title"><div><span className="aw-eyebrow">REFERÊNCIAS / DECISÕES / CONTEXTO</span><h2>Segundo cérebro</h2></div><span className="aw-badge">{k?.enabled?'SINCRONIZAÇÃO AUTORIZADA':'MEMÓRIA LOCAL'}</span></header>
    <p className="aw-caption">Os agentes registram hipóteses, fontes, incertezas e testes durante a operação. Consultam até seis notas relevantes por ciclo, sem outra chamada de IA. O contexto adicional ocupa tokens e pode aumentar o custo de cada chamada. Isso melhora continuidade; não treina o modelo nem garante acertos.</p>
    <p className="aw-caption"><a href="https://github.com/greenspyder/Projeto" target="_blank" rel="noreferrer">greenspyder/Projeto</a> é público. A importação lê até 20 notas em Cerebro/Referencias, Diretrizes e Índice; somente Markdown. Atualize após editar no Obsidian. Nunca guarde chaves, clientes ou informações confidenciais nesse vault.</p>
    <div className="aw-actions"><button className="aw-button aw-secondary" disabled={busy} onClick={()=>void mutate(agentApi.refreshKnowledge,'Repositório consultado; veja as referências disponíveis.')}>Atualizar referências do Projeto</button><button className="aw-button aw-secondary" disabled={busy} onClick={()=>void exportNotes()}>Exportar memória privada (JSON)</button></div>
    <p className="aw-caption">{k?.importedAt?`Última consulta: ${new Date(k.importedAt).toLocaleString('pt-BR')} · ${k.importedCount || 0} notas importadas do repositório`:'Referências ainda não importadas.'} · {k?.notes.length||0} notas disponíveis. Resultados financeiros ficam no servidor e no backup privado; não são enviados ao Projeto.</p>
    {(error||k?.error)&&<p className="aw-caption" role="alert">{error||k?.error}</p>}
    <details><summary>Autorizar escrita automática no Projeto</summary><p className="aw-caption">Crie um token fine-grained somente para Projeto, Contents: Read and write. A conexão da aplicação com HubLoan não concede acesso a outro repositório. A autorização dura 72 horas, até 30 tentativas; erros pausam a sincronização. A conexão inicializa até três referências Markdown se elas ainda não existirem. Depois, somente novas notas de pesquisas em Cerebro/IA/Pesquisas são gravadas; notas existentes não são sobrescritas. A gravação acompanha ciclos ativos.</p>
    <form className="aw-form" onSubmit={e=>{e.preventDefault();void mutate(()=>agentApi.connectKnowledge(key,authorize),'Sincronização autorizada por 72 horas.').then(data=>{if(data){setKey('');setAuthorize(false);}});}}><label>Token GitHub para Projeto<input type="password" value={key} onChange={e=>setKey(e.target.value)} autoComplete="off" /></label><label className="aw-checkbox"><input type="checkbox" checked={authorize} onChange={e=>setAuthorize(e.target.checked)} />Autorizo criar as três referências iniciais e publicar automaticamente resumos futuros de pesquisas, hipóteses e URLs no meu repositório público Projeto. Não colocarei informações confidenciais nos briefings.</label><button className="aw-button aw-secondary" disabled={busy||!authorize||!key.trim()}>Conectar e autorizar</button></form>
    <p className="aw-caption">{k?.usedWrites||0}/{k?.maxWrites||30} tentativas/reservas{ k?.expiresAt?` · Até ${new Date(k.expiresAt).toLocaleString('pt-BR')}`:''}. Pausar não desfaz gravações enviadas.</p><div className="aw-actions"><button className="aw-button aw-secondary" disabled={busy||!k?.enabled} onClick={()=>void mutate(agentApi.pauseKnowledge,'Sincronização pausada.')}>Pausar sincronização</button><button className="aw-button aw-secondary" disabled={busy||!k?.configured} onClick={()=>void mutate(agentApi.disconnectKnowledge,'Token removido; memória preservada.')}>Remover conexão</button></div></details>
    <div className="aw-form"><label>Buscar na memória<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Tema, fonte ou decisão" /></label></div>
    {(k?.notes||[]).filter(n=>(n.title+' '+n.content).toLowerCase().includes(filter.toLowerCase())).slice(-20).reverse().map(n=><details key={n.id}><summary>{n.title} · {n.kind==='research-decision'?'Hipótese da IA':n.kind==='built-in-reference'?'Referência inicial':'Referência importada'}{n.publishedAt?' · Sincronizada':''}</summary><p className="aw-caption">{n.path} · {new Date(n.observedAt).toLocaleString('pt-BR')}</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{n.content}</pre></details>)}
    {!k?.notes.length&&<p className="aw-caption">Nenhuma pesquisa registrada. Você pode importar referências agora; a IA preencherá notas quando um projeto autorizado pesquisar oportunidades.</p>}
  </section>;
}
