import { useState } from 'react';
import { agentApi, type BusinessExperiment, type Workspace } from '../services/agentApi';
type Props={experiment:BusinessExperiment;workspace:Workspace;busy:boolean;mutate:(op:()=>Promise<Workspace>,message?:string)=>Promise<Workspace|null>};
const money=(n:number)=>(n/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function MarketplaceOffer({experiment:e,workspace,busy,mutate}:Props){
 const [error,setError]=useState(''); const offer=e.marketplace;const observation=e.marketplaceMetrics;
 const sample=workspace.missions.find(m=>m.id===e.validation?.sampleId);
 const kit=offer ? `# ${offer.title}\n\nCanal: ${offer.channel} — publicação manual\n\n${offer.description}\n\nTags: ${offer.tags}\n\nPreço proposto: ${money(e.validation?.offer?.priceMinor||0)} BRL (converter e conferir taxas; não validado)\nPrazo: ${e.validation?.offer?.deliveryDays} dias\n\nLicença / direitos: ${offer.license}\n\nEvidência declarada: ${e.validation?.evidence?.url}\nAmostra: ${sample?.title||'Pendente'}\n\nAntes de publicar: revisar a amostra e baixar arquivos/imagens no Armazém; conferir licença, direitos e regras do canal. Etsy: declarar uso de IA quando aplicável e vender somente criação própria elegível. Fiverr: combinar requisitos, revisões, prazo e uso de IA com o cliente. Não prometer CTR ou vendas. HubLoan não publica nem atende pedidos nestes canais.\n\nDepois: registrar URL, período, vendas retidas, receita e reembolsos; lançar taxas, consumo de API e demais custos no experimento.` : '';
 return <details><summary>Oferta e resultados — Fiverr / Etsy / itch.io</summary><p className="aw-caption">1. Evidência e oferta no Modo Primeira Venda. 2. Uma amostra revisada. 3. Publicação manual. 4. Resultado com custos. Não exige conectar Stripe.</p>
 {!e.validation?.offer||!e.validation?.evidence?<p>Preencha a evidência e a oferta acima para começar.</p>:<form className="aw-form" onSubmit={event=>{event.preventDefault();const d=new FormData(event.currentTarget);void mutate(()=>agentApi.experimentAction(e.id,'marketplace-offer',Object.fromEntries(d)),'Kit de oferta salvo; publicação externa continua manual.');}}>
 <div className="aw-columns"><label>Fábrica<select name="factoryId" defaultValue={offer?.factoryId||sample?.factoryId||'factory-thumbnail'}>{workspace.factories?.filter(f=>!f.blocker).map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Canal<select name="channel" defaultValue={offer?.channel||'fiverr'}><option value="fiverr">Fiverr · thumbnails sob demanda</option><option value="etsy">Etsy · downloads originais elegíveis</option><option value="itchio">itch.io · assets</option></select></label></div>
 <label>Título editável<input name="title" required maxLength={140} defaultValue={offer?.title||e.name}/></label><label>Descrição e entregáveis<textarea name="description" required maxLength={4000} defaultValue={offer?.description||`${e.validation.offer.scope}\nPara: ${e.audience}\nPrazo proposto: ${e.validation.offer.deliveryDays} dias.\n${e.validation.offer.criteria}\nCriação assistida por IA, sujeita à revisão humana. Sem garantia de resultados comerciais.`}/></label><label>Tags editáveis<input name="tags" required maxLength={300} defaultValue={offer?.tags||e.audience.slice(0,300)}/></label><label>Licença, direitos e limites de uso<textarea name="license" required maxLength={1000} defaultValue={offer?.license||''} placeholder="Declare apenas direitos que você pode conceder."/></label><button className="aw-button" disabled={busy||Boolean(offer?.observation)||e.ended}>Salvar kit de oferta</button></form>}
 {offer&&<><pre style={{whiteSpace:'pre-wrap'}}>{kit}</pre><button className="aw-button aw-secondary" onClick={()=>{const url=URL.createObjectURL(new Blob([kit],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`oferta-${e.id}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Baixar kit em texto</button> <a href="/agentes/armazem">Baixar arquivos e imagens da amostra</a><p><a href={offer.channel==='fiverr'?'https://www.fiverr.com/start_selling':offer.channel==='etsy'?'https://www.etsy.com/sell':'https://itch.io/game/new'} target="_blank" rel="noreferrer">Abrir marketplace para publicar manualmente</a></p><p className="aw-caption">Status: {offer.status==='prepared-manual'?'Preparado; publicação não confirmada':'Resultados informados por você'}. {e.validationReadiness?.qualityCurrent?'Amostra revisada.':'Revisão da amostra pendente.'}</p>
 <details><summary>Registrar ou corrigir o resultado externo</summary><p>Informe o total acumulado deste teste. Um novo registro substitui o anterior e mantém o histórico; não soma novamente. Use uma oferta exclusiva por experimento. Valores em reais após conversão documentada. Não inclua vendas Stripe.</p><form className="aw-form" onSubmit={event=>{event.preventDefault();setError('');const d=new FormData(event.currentTarget);const input:Record<string,unknown>=Object.fromEntries(d);for(const k of ['grossMinor','refundedMinor']){const v=String(d.get(k)||'');if(!/^\d+(?:[.,]\d{1,2})?$/.test(v)){setError('Valores monetários inválidos.');return;}input[k]=Math.round(Number(v.replace(',','.'))*100);}for(const k of ['sales','visits','leads','humanMinutes','repeatSales'])input[k]=d.get(k)===''?null:Number(d.get(k));void mutate(()=>agentApi.experimentAction(e.id,'marketplace-results',input),'Resultado declarado salvo. Confira e revise os custos.');}}>
 <label>URL pública da oferta<input name="listing" type="url" required defaultValue={offer.observation?.listing}/></label><label>Referência do relatório, sem dados pessoais<input name="reference" required maxLength={500} defaultValue={offer.observation?.reference}/></label><label>Período exato e critério de câmbio, se necessário<input name="period" required maxLength={500} defaultValue={offer.observation?.period} placeholder="Só resultados desta oferta nesta janela; moeda original, câmbio e data."/></label>
 <div className="aw-columns">{[['grossMinor','Receita bruta (R$)'],['refundedMinor','Reembolsos (R$)'],['sales','Vendas retidas']].map(([k,label])=><label key={k}>{label}<input name={k} required inputMode="decimal" defaultValue={offer.observation ? (k==='sales'?offer.observation.sales:offer.observation[k as 'grossMinor'|'refundedMinor']/100):undefined}/></label>)}</div>
 <div className="aw-columns">{[['visits','Visitas'],['leads','Leads'],['humanMinutes','Minutos de trabalho humano'],['repeatSales','Vendas de recompra']].map(([k,label])=><label key={k}>{label} (opcional)<input name={k} type="number" min={0} step={1} defaultValue={offer.observation?.[k as 'visits'|'leads'|'humanMinutes'|'repeatSales']??''}/></label>)}</div><p className="aw-caption">Deixe desconhecidos em branco. Taxas, API e trabalho monetizado entram nos custos abaixo, uma única vez.</p><button className="aw-button" disabled={busy}>Salvar totais declarados</button>{error&&<p role="alert">{error}</p>}</form></details>
 {observation&&<div className="aw-notice"><p>Receita declarada: {money(observation.grossMinor)} · Vendas retidas: {observation.sales} · Resultado: {observation.resultMinor===null?'A apurar':money(observation.resultMinor)}</p><p>Conversão: {observation.conversion===null?'A apurar':`${(observation.conversion*100).toFixed(1)}%`} · Confiança: {observation.confidence}.</p></div>}</>}
 </details>;
}
