import { agentApi, type BusinessExperiment, type Workspace } from '../services/agentApi';
type Props={workspace:Workspace;experiment:BusinessExperiment;busy:boolean;mutate:(op:()=>Promise<Workspace>,message?:string)=>Promise<Workspace|null>};
export function MarketReferences({experiment:e,busy,mutate}:Props){
 const frozen=Boolean(e.validation?.sampleId||e.ended),refs=e.marketReferences||[];
 return <section className="sc-references"><h3>1. Oportunidade · por que criar esta oferta?</h3><p>Compare ofertas reais de vendedores distintos. Preço e posição na busca não comprovam vendas. Astra separa sinais observados, inferências e hipóteses.</p>
 {!frozen&&!refs.length&&<form className="aw-form" onSubmit={ev=>{ev.preventDefault();const d=new FormData(ev.currentTarget);void mutate(()=>agentApi.researchReferences(e.id,String(d.get('query')),d.get('authorize')==='on'),'Pesquisa concluída. Confira as fontes; nenhuma produção ou publicação iniciada.');}}><label>Qual mercado/problema pesquisar?<input name="query" required maxLength={400} defaultValue={`${e.audience}: ${e.hypothesis}`.slice(0,400)}/></label><label className="aw-checkbox"><input name="authorize" type="checkbox" required/>Autorizar pesquisa e análise com IA dentro dos limites do espaço e deste teste.</label><button className="aw-button" disabled={busy||e.referenceResearch?.status==='running'}>Encontrar referências e analisar com Astra</button><small>Até duas chamadas de IA: busca e análise. As reservas são limites de execução, não custos faturados.</small></form>}
 {e.referenceResearch&&<p role="status">Pesquisa: {e.referenceResearch.status} {e.referenceResearch.error}</p>}
 <div className="sc-reference-grid">{refs.map(r=><article className="sc-listing-preview" key={r.id}><h4>{r.product}</h4><p>{r.marketplace} · {r.seller} · {r.category}</p><a href={r.url} target="_blank" rel="noreferrer">Conferir fonte</a><small> · {new Date(r.observedAt).toLocaleDateString('pt-BR')}</small><p><strong>Observação registrada:</strong> {r.observedPrice||'Preço desconhecido'}</p>{r.signals.map((s,i)=><p key={i}>{s.kind}: {s.value} · escopo: {s.scope}</p>)}<p><strong>Características:</strong> {r.features.join('; ')}</p><p><strong>Inferência de quem registrou:</strong> {r.inference}</p><p><strong>Hipótese a testar:</strong> {r.hypothesis}</p><p><strong>Variação original:</strong> {r.opportunity}</p><small>Risco declarado: {r.ipRisk} · Origem: {r.origin}</small></article>)}</div>
 {e.marketComparison&&<aside className="sc-summary"><h4>Padrões entre referências</h4><p>{e.marketComparison.distinctSellers} vendedores distintos · {e.marketComparison.sufficient?'Base suficiente para considerar um teste pequeno':'Evidência insuficiente para tratar como padrão de vencedores'}</p>{e.marketComparison.patterns.map(p=><p key={p.feature}>{p.feature} · {p.sellers} vendedores</p>)}<small>{e.marketComparison.note}</small></aside>}
 {!frozen&&refs.length<5&&<details><summary>Adicionar referência que você conferiu</summary><form className="aw-form" onSubmit={ev=>{ev.preventDefault();const d=new FormData(ev.currentTarget);const url=String(d.get('url'));void mutate(()=>agentApi.experimentAction(e.id,'market-reference',{...Object.fromEntries(d),features:String(d.get('features')).split(';').map(s=>s.trim()).filter(Boolean),observedPrice:d.get('observedPrice')||null,observedAt:new Date(String(d.get('observedAt'))).toISOString(),signals:d.get('signal')?[{kind:d.get('kind'),value:d.get('signal'),scope:d.get('scope'),sourceUrl:url}]:[]}),'Referência registrada como observação sua; nenhuma venda presumida.');}}>
 {([['marketplace','Marketplace'],['seller','Vendedor'],['category','Categoria'],['product','Produto'],['url','URL da oferta'],['observedPrice','Preço e moeda (opcional)'],['features','Características gerais (separar com ;)'],['inference','Inferência'],['hypothesis','Hipótese a testar'],['opportunity','Nossa variação original']] as const).map(([name,label])=><label key={name}>{label}<input name={name} type={name==='url'?'url':'text'} required={name!=='observedPrice'} maxLength={name==='url'?1500:500}/></label>)}
 <label>Quando você conferiu a fonte?<input name="observedAt" type="datetime-local" required/></label><label>Tipo de sinal<select name="kind"><option value="review">Avaliações</option><option value="paid_request">Pedido público pago</option><option value="bestseller">Etiqueta bestseller</option><option value="sales">Vendas explícitas na fonte</option><option value="favorite">Favoritos</option></select></label><label>Sinal observado (opcional)<input name="signal" maxLength={300}/></label><label>Escopo do sinal (produto, loja, período)<input name="scope" maxLength={150}/></label><label>Risco de similaridade/direitos<select name="ipRisk"><option value="unknown">Não avaliado</option><option value="low">Baixo, segundo minha análise</option><option value="high">Alto</option></select></label><button disabled={busy} className="aw-button">Registrar referência</button></form></details>}
 </section>;
}
export function OriginalityReview({experiment:e,busy,mutate}:Props){return <section className="sc-originality"><h3>Similaridade e originalidade</h3><p>Compare a amostra com cada referência. Confira composição própria, textos, imagens, marcas, personagens e licença. A conferência humana não é uma garantia jurídica.</p><p>{e.originalityCurrent?'✓ Originalidade da versão atual revisada':'Revisão de originalidade pendente ou desatualizada'}</p><form className="aw-form" onSubmit={ev=>{ev.preventDefault();const d=new FormData(ev.currentTarget);void mutate(()=>agentApi.experimentAction(e.id,'originality-review',{approved:d.get('approved')==='yes',reason:d.get('reason')}),'Revisão de originalidade registrada para esta versão.');}}><label>Resultado<select name="approved"><option value="no">Risco identificado / revisão necessária</option><option value="yes">Conferi: variação própria e direitos suficientes</option></select></label><label>O que foi comparado e quais mudanças tornam a oferta original?<textarea name="reason" required maxLength={800}/></label><button className="aw-button" disabled={busy||!e.validation?.sampleId}>Registrar minha revisão</button></form></section>;}
