import { useState } from 'react';
import type { FormEvent } from 'react';
import { Radio, ExternalLink, Pause } from 'lucide-react';
import { agentApi } from '../services/agentApi';
import type { Workspace, MarketingChannel, MarketingSettings, SharingChannel } from '../services/agentApi';
type Props = { workspace: Workspace; busy: boolean; mutate: (operation: () => Promise<Workspace>, success?: string) => Promise<Workspace | null> };
const names = { mastodon: 'Mastodon', telegram: 'Telegram', bluesky: 'Bluesky', whatsapp:'WhatsApp', linkedin:'LinkedIn', reddit:'Reddit', instagram:'Instagram', tiktok:'TikTok' };
const sharing:SharingChannel[] = ['whatsapp','linkedin','reddit','instagram','tiktok'];
const states: Record<string, string> = { prepared:'Material preparado · publicação manual não verificada', publishing: 'Enviando', posted: 'Publicado', uncertain: 'Conferir no canal', skipped: 'Tentativa encerrada' };
const money = (n: number) => (n / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
export function MarketingPanel({ workspace, busy, mutate }: Props) {
  const marketing = workspace.marketing;
  const [productId,setProductId] = useState(''), [shareChannel,setShareChannel] = useState<SharingChannel>('whatsapp'), [copyNotice,setCopyNotice] = useState('');
  const products = workspace.shop?.products.filter(p=>p.listed) || [];
  async function copy(text:string) {try{await navigator.clipboard.writeText(text);setCopyNotice('Texto e link copiados. Revise e publique no canal escolhido.');}catch{setCopyNotice('Não foi possível copiar. Selecione o texto da oferta abaixo e copie manualmente.');}}
  const [channel, setChannel] = useState<MarketingChannel>('mastodon'), [key, setKey] = useState(''), [target, setTarget] = useState(''), [authorize, setAuthorize] = useState(false);
  const [settings, setSettings] = useState<MarketingSettings>({ enabled: marketing?.enabled || false, intervalMinutes: marketing?.intervalMinutes || 240, maxPosts: marketing?.maxPosts || 6 });
  const [checked, setChecked] = useState<Record<string, boolean>>({});
  async function connect(e: FormEvent) { e.preventDefault(); const result = await mutate(() => agentApi.connectMarketing(channel, key, target, authorize), 'Canal conectado. Ative a divulgação automática abaixo.'); if (result) { setKey(''); setTarget(''); setAuthorize(false); setSettings(s => ({ ...s, enabled: false })); } }
  async function configure(e: FormEvent) { e.preventDefault(); await mutate(() => agentApi.configureMarketing(settings), 'Divulgação configurada. A autorização vale por até 72 horas.'); }
  const hasChannel = marketing?.channels.some(c => c.configured);
  return <section className="aw-panel" id="marketing"><div className="aw-section-title"><div><p className="aw-eyebrow">OFERTAS / DISTRIBUIÇÃO / RESULTADOS</p><h2><Radio size={21} /> Divulgação</h2></div><span className="aw-badge">{marketing?.enabled ? 'AUTORIZADA' : 'PAUSADA'}</span></div>
    <p className="aw-caption">Produtos publicados na sua loja real entram na fila de anúncios. A aplicação publica preço, formato, identificação de uso de IA e link rastreável nos canais conectados. Os resultados entram nas próximas análises das IAs; não há compra de anúncios ou mensagens privadas.</p>
    <div className="aw-publishing-modes"><article><h3>Envio automático</h3><p>Bluesky, Mastodon e Telegram. Conecte sua conta e autorize os envios com limite e prazo.</p></article><article><h3>Compartilhar uma oferta</h3><p>WhatsApp, LinkedIn, Reddit, Instagram e TikTok. Prepare texto e link rastreável; você revisa e publica.</p></article></div><details><summary>Conectar um canal de divulgação</summary><form className="aw-form" onSubmit={connect}><label>Canal<select value={channel} onChange={e => { setChannel(e.target.value as MarketingChannel); setKey(''); setTarget(''); setAuthorize(false); }}><option value="mastodon">Mastodon · mastodon.social</option><option value="telegram">Telegram · seu canal</option><option value="bluesky">Bluesky · seu perfil público</option></select></label>
      {channel === 'bluesky' ? <ol><li>Na sua conta Bluesky, abra Configurações → Privacidade e segurança → Senhas de aplicativo.</li><li>Crie uma senha para HubLoan, sem acesso a mensagens privadas. Use apenas essa senha, não a senha principal.</li><li>Informe seu identificador, por exemplo nome.bsky.social. Esta integração suporta contas hospedadas pelo Bluesky.</li></ol> : channel === 'mastodon' ? <ol><li>Use uma conta em <a href="https://mastodon.social" target="_blank" rel="noreferrer">mastodon.social</a>. Nesta versão, outras instâncias não são suportadas.</li><li>Em Preferências → Desenvolvimento → Nova aplicação, habilite os escopos <code>read:accounts</code> e <code>write:statuses</code>.</li><li>Copie “Seu token de acesso” da aplicação. Confira se as regras da instância permitem seus anúncios e o uso de IA.</li></ol> : <ol><li>Crie seu bot com <a href="https://t.me/BotFather" target="_blank" rel="noreferrer">@BotFather</a>, usando /newbot, e copie o token.</li><li>Adicione o bot como administrador do seu canal com permissão de publicar mensagens.</li><li>Informe o @nome público ou ID -100… do canal. Grupos e conversas privadas não são suportados.</li></ol>}
      <label>{channel === 'bluesky' ? 'Senha de aplicativo Bluesky' : `Token ${names[channel]}`}<input type="password" autoComplete="off" value={key} maxLength={1000} onChange={e => setKey(e.target.value)} required /></label>{channel === 'bluesky' && <label>Identificador Bluesky<input value={target} maxLength={253} onChange={e=>setTarget(e.target.value)} placeholder="nome.bsky.social" required /></label>}{channel === 'telegram' && <label>Seu canal Telegram<input value={target} maxLength={50} onChange={e => setTarget(e.target.value)} placeholder="@minha_loja" required /></label>}
      <label className="aw-checkbox"><input type="checkbox" checked={authorize} onChange={e => setAuthorize(e.target.checked)} /> Este canal é administrado por mim e autorizo publicar ofertas nele</label><small>O token fica criptografado no servidor. Conectar ou remover um canal pausa a divulgação até você ativá-la novamente.</small><button className="aw-button" disabled={busy || !authorize}>Conectar {names[channel]}</button></form></details>
    {marketing?.channels.filter(c => c.configured).map(c => <article className="aw-project" key={c.kind}><h3>{names[c.kind]} · {c.name}</h3><button className="aw-button aw-secondary" disabled={busy} onClick={() => void mutate(() => agentApi.disconnectMarketing(c.kind), 'Canal removido. Divulgação pausada.')}>Desconectar canal</button></article>)}
    {hasChannel && <form className="aw-form" onSubmit={configure}><div className="aw-columns"><label>Intervalo entre anúncios (minutos)<input type="number" min={120} max={1440} value={settings.intervalMinutes} onChange={e => setSettings(s => ({ ...s, intervalMinutes: Number(e.target.value) }))} required /></label><label>Limite total desta autorização<input type="number" min={1} max={20} value={settings.maxPosts} onChange={e => setSettings(s => ({ ...s, maxPosts: Number(e.target.value) }))} required /></label></div><label className="aw-checkbox"><input type="checkbox" checked={settings.enabled} onChange={e => setSettings(s => ({ ...s, enabled: e.target.checked }))} /> Publicar automaticamente ofertas atuais e futuras nos canais conectados por até 72 horas</label><small>Requer loja aberta com Stripe real. Um anúncio por produto/canal; no máximo três tentativas por canal em 24 horas. O primeiro anúncio entra no próximo ciclo do servidor. Falha de confirmação pausa os envios. Funciona enquanto o servidor estiver ativo; hospedagem que adormece interrompe o processamento.</small><div className="aw-actions"><button className="aw-button" disabled={busy}>Salvar divulgação e autorização</button><button type="button" className="aw-button aw-secondary" disabled={busy || !marketing?.enabled} onClick={() => void mutate(() => agentApi.configureMarketing({ ...settings, enabled: false }), 'Divulgação pausada. Publicações existentes continuam nos canais.')}><Pause size={15} /> Pausar agora</button></div></form>}
    <p className="aw-caption">{marketing?.grantUsed || 0}/{marketing?.maxPosts || 6} tentativas desta autorização{marketing?.expiresAt ? ` · validade até ${new Date(marketing.expiresAt).toLocaleString('pt-BR')}` : ''}. Uma publicação não garante alcance ou compradores. O Telegram precisa de público no seu canal; o Mastodon também depende de interesse e distribuição.</p>
    {marketing?.error && <p className="aw-error" role="alert">{marketing.error}</p>}
    <details><summary>Preparar divulgação em outros canais</summary><p>Escolha uma oferta publicada. Nenhuma mensagem é enviada por esta ação. Use espaços que permitem divulgação; não há envio em massa ou contato privado automático.</p>{!products.length ? <p>Publique uma entrega na <a href="#shop">loja</a> para preparar sua primeira campanha.</p> : <form className="aw-form" onSubmit={e=>{e.preventDefault();void mutate(()=>agentApi.prepareCampaign(productId || products[0].id,shareChannel),'Material preparado. Copie o texto na campanha abaixo; a publicação depende de você.');}}><label>Produto<select value={productId || products[0].id} onChange={e=>setProductId(e.target.value)}>{products.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Canal de compartilhamento<select value={shareChannel} onChange={e=>setShareChannel(e.target.value as SharingChannel)}>{sharing.map(c=><option key={c} value={c}>{names[c]}</option>)}</select></label><p className="aw-caption">Para Instagram e TikTok, use o texto como apoio e o link onde a conta permitir. Esta ação não cria vídeo nem conecta essas contas. Downloads e prévias estão no <a href="#missions">armazém</a>.</p><button className="aw-button" disabled={busy}>Preparar texto e link</button></form>}</details>
    {copyNotice && <p role="status">{copyNotice}</p>}
    <h3>Campanhas e vendas atribuídas</h3><p className="aw-caption">{marketing?.note || 'Acessos e compras aparecem após publicações reais. Sem dados, não há resultados estimados.'} Taxas Stripe, APIs, impostos e trabalho precisam ser contabilizados separadamente.</p>
    {!marketing?.campaigns.length && <p className="aw-caption">Nenhuma campanha. Conecte um canal automático ou prepare uma oferta para compartilhar.</p>}
    {marketing?.campaigns.slice().reverse().map(c => <article className="aw-project" key={c.id}><h3>{c.title}</h3><p>{names[c.channel]} · {states[c.status] || c.status} · {new Date(c.createdAt).toLocaleString('pt-BR')}</p><p>{c.visits} acessos registrados · {c.purchases} compras reais · {money(c.grossMinor)} brutos · {money(c.refundedMinor)} reembolsados</p><details open={c.status === 'prepared'}><summary>Texto e link da oferta</summary><p style={{ whiteSpace: 'pre-wrap' }}>{c.text}</p><button className="aw-button aw-secondary" onClick={()=>void copy(c.text)}>Copiar texto e link</button><a href={c.link} target="_blank" rel="noreferrer">Abrir oferta rastreável</a></details>{c.url && <a className="aw-button aw-secondary" href={c.url} target="_blank" rel="noreferrer"><ExternalLink size={15} /> Ver publicação no canal</a>}{c.error && <p className="aw-caption">{c.error}</p>}{c.status === 'uncertain' && <><label className="aw-checkbox"><input type="checkbox" checked={checked[c.id] || false} onChange={e => setChecked(s => ({ ...s, [c.id]: e.target.checked }))} /> Conferi o canal e quero encerrar esta tentativa sem reenviar este produto</label><button className="aw-button aw-secondary" disabled={busy || !checked[c.id]} onClick={() => void mutate(() => agentApi.skipCampaign(c.id), 'Tentativa encerrada. Ative a divulgação para continuar com outros produtos.')}>Encerrar tentativa</button></>}</article>)}
  </section>;
}
