import { ItchRelease } from './ItchRelease';
import { EtsyPublication } from './EtsyConnection';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { agentApi, type BusinessExperiment, type Workspace } from '../services/agentApi';
import { factoryChannels, marketplaceNames, type MarketplaceId } from '../services/salesChannels';
type Props = { stage?: 'prepare'|'review'|'publish'|'results'; experiment: BusinessExperiment; workspace: Workspace; busy: boolean; mutate: (op: () => Promise<Workspace>, message?: string) => Promise<Workspace|null> };
const money = (n:number) => (n/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function download(blob:Blob, filename:string) { const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
export function MarketplaceOffer({experiment:e,workspace:w,busy,mutate,stage}:Props) {
  const [error,setError]=useState(''),[copied,setCopied]=useState(''),[uploadConsent,setUploadConsent]=useState(false),[downloading,setDownloading]=useState(false);
  const offer=e.marketplace,observation=e.marketplaceMetrics;
  const sample=w.missions.find(m=>m.id===e.validation?.sampleId);
  const [factoryId,setFactoryId]=useState(e.salesChannel?.factoryId || offer?.factoryId || sample?.factoryId || w.factories?.find(f=>f.kind==='thumbnail')?.id || '');
  const factory=w.factories?.find(f=>f.id===factoryId);
  const [channel,setChannel]=useState<MarketplaceId>((e.salesChannel?.channel || offer?.channel || (factory && factoryChannels(factory)[0]) || 'fiverr') as MarketplaceId);
  const show=(part:Props['stage'])=>!stage || stage===part;
  const locked=Boolean(e.salesChannel || offer?.observation || offer?.publication);
  const kit=offer ? `# ${offer.title}\n\nCanal: ${offer.channel}\n\n${offer.description}\n\nCategoria: ${offer.category||'Conferir no marketplace'}\n\nPacotes: ${offer.packages||'Definir no marketplace'}\n\nFAQ: ${offer.faq||'Conferir requisitos'}\n\nRequisitos do comprador: ${offer.requirements||'Conferir'}\n\nTags: ${offer.tags}\n\nPreço proposto: ${money(e.validation?.offer?.priceMinor||0)} BRL — converter e conferir taxas.\nPrazo: ${e.validation?.offer?.deliveryDays} dias\n\nLicença / direitos: ${offer.license}\n\nAmostra: ${sample?.title || 'Pendente'}\n\nRevise amostra, arquivos, direitos e condições antes de publicar. Etsy: criação própria elegível, declarar IA quando aplicável. Fiverr: combinar requisitos, revisões, prazo e uso de IA. Sem garantia de CTR ou vendas. Atendimento externo manual.\n` : '';
  const copy=async(text:string,label:string)=>{try{await navigator.clipboard.writeText(text);setCopied(`${label} copiado.`);}catch{setError('Não foi possível copiar. Baixe o kit em texto.');}};
  async function files() { if(!sample)return;setDownloading(true);setError('');try{if(sample.hasArtifact)download(await agentApi.image(sample.id),sample.artifactFilename||`amostra-${sample.id}.zip`);else if(sample.output)download(new Blob([sample.output],{type:'text/markdown;charset=utf-8'}),`amostra-${sample.id}.md`);}catch(err){setError(err instanceof Error?err.message:'Falha ao baixar a amostra.');}finally{setDownloading(false);} }
  return <section className="sc-offer" aria-label="Preparação da oferta no marketplace">
    {!stage && <h3>Oferta no marketplace</h3>}
    {show('prepare') && <>{e.validation?.evidence&&e.validation?.offer&&!offer?.publication&&!offer?.etsy&&<form className="aw-form sc-summary" onSubmit={ev=>{ev.preventDefault();const d=new FormData(ev.currentTarget);void mutate(()=>agentApi.prepareOffer(e.id,String(d.get('license')),d.get('authorize')==='on'),'Apresentação preparada por IA. Revise campos, preços e direitos antes de publicar.');}}><h3>Preparar apresentação com os agentes</h3><label>Licença e direitos que você pode conceder<textarea name="license" required maxLength={1000} defaultValue={offer?.license}/></label><label className="aw-checkbox"><input type="checkbox" name="authorize" required/>Autorizar uma chamada de IA dentro dos limites para preparar título, descrição, tags e, no Fiverr, pacotes/FAQ.</label><button className="aw-button" disabled={busy}>Preparar oferta original com IA</button></form>}<h3>Título e apresentação da oferta</h3>{!e.validation?.offer || !e.validation?.evidence ? <p className="aw-notice">Registre o problema observado e defina a oferta no Modo Primeira Venda acima. Depois, prepare o anúncio aqui.</p> : <form key={offer?.title+String(offer?.description)} className="aw-form" onSubmit={event=>{event.preventDefault();const d=new FormData(event.currentTarget);void mutate(()=>agentApi.experimentAction(e.id,'marketplace-offer',{...Object.fromEntries(d),factoryId,channel}),'Kit de oferta salvo. A publicação ainda não foi realizada.');}}>
      <div className="aw-columns"><label>Fábrica<select value={factoryId} disabled={locked} onChange={event=>{setFactoryId(event.target.value);const f=w.factories?.find(f=>f.id===event.target.value);if(f)setChannel(factoryChannels(f)[0]);}}>{w.factories?.filter(f=>factoryChannels(f).length>0).map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Canal<select value={channel} disabled={locked} onChange={event=>setChannel(event.target.value as MarketplaceId)}>{(factory?factoryChannels(factory):[]).map(c=><option key={c} value={c}>{marketplaceNames[c]}</option>)}</select></label></div>
      <p className="aw-caption">Preço proposto: {money(e.validation.offer.priceMinor)} · Prazo: {e.validation.offer.deliveryDays} dias. Definidos na oferta acima; confira conversão e taxas do canal.</p>
      <label>Título do {channel==='fiverr'?'Gig':'listing'}<input name="title" required maxLength={channel==='fiverr'?80:140} defaultValue={offer?.title||e.name}/></label><label>Descrição e entregáveis<textarea name="description" required maxLength={4000} rows={5} defaultValue={offer?.description||`${e.validation.offer.scope}\nPara: ${e.audience}\nPrazo: ${e.validation.offer.deliveryDays} dias.\n${e.validation.offer.criteria}\nCriação assistida por IA, com revisão humana. Sem garantia de resultados comerciais.`}/></label><label>Tags<input name="tags" required maxLength={300} defaultValue={offer?.tags||e.audience.slice(0,300)}/></label><label>Licença, direitos e limites de uso<textarea name="license" required maxLength={1000} defaultValue={offer?.license||''} placeholder="Declare somente direitos que você pode conceder."/></label>{channel==='fiverr'&&<>{(['category','packages','faq','requirements'] as const).map(field=><label key={field}>{({category:'Categoria / subcategoria a conferir',packages:'Basic / Standard / Premium: entregáveis, preços, revisões e prazo',faq:'FAQ original',requirements:'O que o comprador precisa enviar'})[field]}<textarea name={field} maxLength={field==='category'?150:1500} defaultValue={offer?.[field]}/></label>)}</>}<button className="aw-button" disabled={busy||Boolean(offer?.observation||offer?.publication)||e.ended}>Salvar apresentação da oferta</button>{(offer?.observation||offer?.publication)&&<small>Oferta já publicada/informada: preserve este registro e use outro teste para uma nova oferta.</small>}</form>}</>}
    {show('review') && <><h3>Confira exatamente o que será publicado</h3>{offer ? <article className="sc-listing-preview"><span className="sc-status sc-manual">{marketplaceNames[offer.channel as MarketplaceId]} · prévia privada</span><h3>{offer.title}</h3><p className="sc-description">{offer.description}</p><p><strong>Preço proposto:</strong> {money(e.validation?.offer?.priceMinor||0)} · <strong>Prazo:</strong> {e.validation?.offer?.deliveryDays} dias</p><p><strong>Tags:</strong> {offer.tags}</p><p><strong>Licença:</strong> {offer.license}</p><p><strong>Amostra:</strong> {sample?.title||'Ainda não criada'} · {sample?.phase||'Pendente'}</p><div className="aw-actions"><button className="aw-button aw-secondary" onClick={()=>download(new Blob([kit],{type:'text/markdown;charset=utf-8'}),`oferta-${e.id}.md`)}>Baixar kit completo</button><button className="aw-button aw-secondary" disabled={!sample?.hasArtifact&&!sample?.output || downloading} onClick={()=>void files()}>Baixar arquivos da amostra</button>{sample&&<Link className="aw-button aw-secondary" to={`/agentes/armazem?mission=${sample.id}#terminal`}>Ver amostra no armazém</Link>}</div><p className="aw-caption">Os arquivos baixados são a entrega existente, sem imagens ou resultados simulados. Examine-os antes de registrar a revisão abaixo.</p></article> : <p>Prepare e salve a apresentação da oferta na etapa anterior.</p>}</>}
    {show('publish') && <>{offer?.channel==='etsy'&&<EtsyPublication experimentId={e.id} workspace={w} busy={busy} mutate={mutate}/>}<h3>Colocar a oferta no ar</h3>{!offer ? <p>Salve o kit da oferta antes de publicar.</p> : <><p className="aw-notice">{e.validationReadiness?.qualityCurrent ? 'Revisão da amostra registrada.' : 'Amostra ainda sem revisão válida. Volte a Revisar antes de publicar.'}</p><div className="sc-publish-actions"><button className="aw-button aw-secondary" onClick={()=>void copy(offer.title,'Título')}>Copiar título</button><button className="aw-button aw-secondary" onClick={()=>void copy(offer.description,'Descrição')}>Copiar descrição</button><button className="aw-button aw-secondary" onClick={()=>void copy(offer.tags,'Tags')}>Copiar tags</button><button className="aw-button aw-secondary" onClick={()=>download(new Blob([kit],{type:'text/markdown;charset=utf-8'}),`oferta-${e.id}.md`)}>Baixar kit completo</button><button className="aw-button aw-secondary" disabled={!sample?.hasArtifact&&!sample?.output || downloading} onClick={()=>void files()}>Baixar amostra / arquivos</button></div>
      <p>{offer.channel==='fiverr' ? 'Você publica o Gig e atende os pedidos no Fiverr. HubLoan não recebe nem entrega pedidos automaticamente.' : offer.channel==='etsy' ? 'Você publica o listing no Etsy, envia arquivos e informa uso de IA quando aplicável. Não há OAuth Etsy conectado.' : 'A criação da página, preço e recebimento são configurados no itch.io. Você pode publicar manualmente ou usar o envio de pack abaixo.'}</p>
      {e.validationReadiness?.qualityCurrent && !e.ended ? <a className="aw-button" href={offer.channel==='fiverr'?'https://www.fiverr.com/start_selling':offer.channel==='etsy'?'https://www.etsy.com/sell':'https://itch.io/game/new'} target="_blank" rel="noreferrer">Abrir {marketplaceNames[offer.channel as MarketplaceId]} e publicar manualmente ↗</a> : <p className="aw-caption">O atalho de publicação fica disponível após a revisão, dentro do prazo do teste.</p>}
      {offer.channel==='itchio' && <div className="sc-integrated-upload"><h3>Enviar pack pela integração itch.io</h3><p>Destino: {sample&&w.commerce?.targets[sample.kind]?.title || 'Não configurado'}. Licença: {w.commerce?.license || 'Não configurada'}.</p><p className="aw-caption">Upload para uma página existente. Não altera o preço nem comprova vendas. Sua página pode disponibilizar os arquivos aos compradores.</p>{sample?.publication?.status==='uploaded' ? <p className="aw-notice">Upload confirmado. Confira a visibilidade na página: <a href={sample.publication.target.url} target="_blank" rel="noreferrer">{sample.publication.target.title}</a></p> : <>{sample&&<ItchRelease mission={sample} workspace={w} busy={busy} mutate={mutate}/>}<label className="aw-checkbox"><input type="checkbox" checked={uploadConsent} onChange={ev=>setUploadConsent(ev.target.checked)}/>Autorizo o envio desta amostra revisada ao destino e com a licença mostrados acima.</label><button className="aw-button" disabled={busy||sample?.status!=="approved"||!sample?.itchRelease||!uploadConsent||!e.validationReadiness?.qualityCurrent||e.ended||!sample?.hasArtifact||!w.commerce?.configured||!w.commerce?.license||!w.commerce?.targets[sample?.kind||'']||['uploading','uncertain'].includes(sample?.publication?.status||'')} onClick={()=>void mutate(async()=>{await agentApi.experimentAction(e.id,'validation-itch-release',{authorize:true});return agentApi.publishPack(sample!.id);},'Envio confirmado pelo itch.io. Confira a página; vendas continuam desconhecidas.').then(result=>{if(result)setUploadConsent(false);})}>Enviar amostra revisada ao itch.io</button></>}<Link to="/agentes/conexoes#commerce">Configurar destino, licença e limite / conferir upload incerto</Link></div>}
      <form className="aw-form sc-publication-report" onSubmit={ev=>{ev.preventDefault();const d=new FormData(ev.currentTarget);void mutate(()=>agentApi.experimentAction(e.id,'marketplace-published',{listing:d.get('listing'),confirm:d.get('confirm')==='on'}),'Publicação informada por você; nenhuma venda foi presumida.');}}><h3>Já publicou? Registre o endereço</h3><p>Abrir o marketplace não confirma publicação. Informe a URL após verificar que a oferta está no ar.</p><label>URL pública do Gig / listing<input name="listing" type="url" required defaultValue={offer.publication?.listing||offer.observation?.listing||sample?.publication?.target.url||''}/></label><label className="aw-checkbox"><input name="confirm" type="checkbox" required/>Conferi a página publicada. Este registro é meu relato, sem verificação pela API.</label><button className="aw-button aw-secondary" disabled={busy}>Registrar publicação</button>{offer.publication&&<p className="aw-caption">Publicação informada em {new Date(offer.publication.at).toLocaleString('pt-BR')}. Resultado comercial ainda depende das vendas e custos registrados.</p>}</form></>}</>}
    {show('results') && <>{offer?.etsy&&<EtsyPublication experimentId={e.id} workspace={w} busy={busy} mutate={mutate}/>}<h3>Vendas e resultados observados</h3>{!offer ? <p>Prepare uma oferta antes de registrar os resultados.</p> : <>{!offer.etsy&&<><p>Informe os totais acumulados desta oferta na janela do teste. Corrigir substitui o registro anterior, sem somar novamente. Valores em reais após conversão documentada; não inclua vendas Stripe.</p><form className="aw-form" onSubmit={event=>{event.preventDefault();setError('');const d=new FormData(event.currentTarget);const input:Record<string,unknown>=Object.fromEntries(d);for(const k of ['grossMinor','refundedMinor']){const v=String(d.get(k)||'');if(!/^\d+(?:[.,]\d{1,2})?$/.test(v)){setError('Valores monetários inválidos.');return;}input[k]=Math.round(Number(v.replace(',','.'))*100);}for(const k of ['sales','visits','leads','humanMinutes','repeatSales'])input[k]=d.get(k)===''?null:Number(d.get(k));void mutate(()=>agentApi.experimentAction(e.id,'marketplace-results',input),'Totais declarados salvos. Lance taxas e demais custos abaixo.');}}>
      <label>URL pública da oferta<input name="listing" type="url" required defaultValue={offer.observation?.listing||offer.publication?.listing}/></label><label>Referência do relatório, sem dados pessoais<input name="reference" required maxLength={500} defaultValue={offer.observation?.reference}/></label><label>Período exato e conversão de moeda<input name="period" required maxLength={500} defaultValue={offer.observation?.period} placeholder="Janela, moeda original, câmbio e data, quando aplicável."/></label><div className="aw-columns">{[['grossMinor','Receita bruta (R$)'],['refundedMinor','Reembolsos (R$)'],['sales',offer.channel==='fiverr'?'Pedidos pagos retidos':'Vendas retidas']].map(([k,label])=><label key={k}>{label}<input name={k} required inputMode="decimal" defaultValue={offer.observation ? k==='sales'?offer.observation.sales:offer.observation[k as 'grossMinor'|'refundedMinor']/100 : undefined}/></label>)}</div><div className="aw-columns">{[['visits','Visitas'],['leads','Leads'],['humanMinutes','Minutos de trabalho humano'],['repeatSales','Vendas de recompra']].map(([k,label])=><label key={k}>{label} (opcional)<input name={k} type="number" min={0} step={1} defaultValue={offer.observation?.[k as 'visits'|'leads'|'humanMinutes'|'repeatSales']??''}/></label>)}</div><small>Desconhecido? Deixe os campos opcionais em branco. Taxas e outros custos são registrados abaixo, uma única vez.</small><button className="aw-button" disabled={busy}>Salvar totais declarados</button></form></>}{observation ? <p className="sc-summary">Receita: {money(observation.grossMinor)} · Vendas: {observation.sales} · Resultado: {observation.resultMinor===null?'A apurar':money(observation.resultMinor)} · Conversão: {observation.conversion===null?'Desconhecida':`${(observation.conversion*100).toFixed(1)}%`}. Origem: {observation.confidence}.</p> : <p className="aw-notice">Resultado desconhecido. Nenhuma observação de vendas registrada.</p>}</>}</>}
    {copied&&<p role="status">{copied}</p>}{error&&<p role="alert">{error}</p>}
  </section>;
}
