import { useState } from 'react';
import type { FormEvent } from 'react';
import { agentApi } from '../services/agentApi';
import type { MarketDecision, Workspace } from '../services/agentApi';
type Props = { projectId: string; decisions: MarketDecision[]; busy: boolean; blocked: boolean; mutate: (operation: () => Promise<Workspace>, success?: string) => Promise<Workspace | null> };
function ExperimentForm({ projectId, decision, busy, blocked, mutate }: Omit<Props, 'decisions'> & { decision: MarketDecision }) {
  const [visits, setVisits] = useState(decision.feedback?.visits || 0);
  const [sales, setSales] = useState(decision.feedback?.sales || 0);
  const [revenue, setRevenue] = useState(decision.feedback?.revenue || 0);
  const [cost, setCost] = useState(decision.feedback?.cost || 0);
  const [evidence, setEvidence] = useState(decision.feedback?.evidence || '');
  async function submit(event: FormEvent) {
    event.preventDefault();
    await mutate(() => agentApi.experiment(projectId, decision.id, { visits, sales, revenue, cost, evidence }), 'Resultado informado salvo. A próxima análise poderá usá-lo; não é verificação automática da loja.');
  }
  return <details><summary>Registrar resultados do teste comercial</summary><p className="aw-caption">Publique a oferta e faça o teste indicado. Registre o período e os números do seu painel. Estes dados são informados por você; o sistema ainda não mede tráfego ou vendas sozinho. Custos devem incluir taxas, publicidade, produção e API; resultado líquido não é apuração contábil.</p><form className="aw-form" onSubmit={submit}><div className="aw-project-fields"><label>Visitas à oferta<input type="number" min={0} max={100000000} value={visits} onChange={e => setVisits(Number(e.target.value))} required /></label><label>Vendas<input type="number" min={0} max={visits} value={sales} onChange={e => setSales(Number(e.target.value))} required /></label><label>Receita recebida (R$)<input type="number" min={0} step="0.01" value={revenue} onChange={e => setRevenue(Number(e.target.value))} required /></label><label>Custos totais (R$)<input type="number" min={0} step="0.01" value={cost} onChange={e => setCost(Number(e.target.value))} required /></label></div><label>Período e referência do resultado<textarea value={evidence} onChange={e => setEvidence(e.target.value)} placeholder="Ex.: painel da minha loja, teste entre 2 e 5 de outubro; visitas e pagamentos confirmados." maxLength={1000} required /></label><button className="aw-button" disabled={busy || blocked}>Salvar resultados informados</button>{blocked && <small>Aguarde a tarefa em andamento para registrar.</small>}</form></details>;
}
export function MarketDecisions(props: Props) {
  return <div className="aw-market-decisions">{[...props.decisions].reverse().map(decision => <section className="aw-market-decision" key={decision.id}><p className="aw-eyebrow">PESQUISA EM {new Date(decision.observedAt).toLocaleString('pt-BR')}</p><h4>{decision.selected ? `Hipótese escolhida: ${decision.selected.title}` : 'Pesquisa sem oportunidade viável'}</h4><p className="aw-caption">Pontuação comparativa estimada pela IA, não previsão de retorno financeiro. Pesquisar hoje não significa que todos os sinais publicados sejam recentes.</p><div className="aw-market-table"><table><thead><tr><th>Oportunidade</th><th>Demanda</th><th>Competição favorável</th><th>Produção</th><th>Distribuição</th><th>Evidência</th><th>Total</th></tr></thead><tbody>{decision.candidates.map(candidate => <tr key={candidate.id}><td>{candidate.title}{candidate.id === decision.selected?.id ? ' · escolhida' : ''}</td><td>{candidate.scores.demand}/5</td><td>{candidate.scores.competition}/5</td><td>{candidate.scores.feasibility}/5</td><td>{candidate.scores.distribution}/5</td><td>{candidate.scores.evidence}/5</td><td>{candidate.score}/100</td></tr>)}</tbody></table></div><p className="aw-caption">Pesos: demanda 25%, competição favorável 15%, produção 25%, distribuição 15%, evidência 20%.</p>{decision.candidates.map(candidate => <details key={candidate.id}><summary>{candidate.title} — justificativa e fontes</summary><p><strong>Público:</strong> {candidate.audience}</p><p>{candidate.rationale}</p><p><strong>Incertezas:</strong> {candidate.uncertainty}</p><p><strong>Teste proposto:</strong> {candidate.test}</p><div className="aw-sources">{candidate.sourceUrls.map(url => <a key={url} href={url} target="_blank" rel="noreferrer">{decision.sources.find(source => source.url === url)?.title || url}</a>)}</div></details>)}{decision.selected && <><p><strong>Próximo teste:</strong> {decision.selected.test}</p>{decision.feedback && <p className="aw-notice">Informado pelo usuário, sem integração: {decision.feedback.sales} vendas / {decision.feedback.visits} visitas · Receita R$ {decision.feedback.revenue.toFixed(2)} · Custos R$ {decision.feedback.cost.toFixed(2)} · Resultado líquido informado R$ {decision.feedback.net.toFixed(2)}</p>}<ExperimentForm {...props} decision={decision} /></>}<details><summary>Relatório original da pesquisa</summary><pre className="aw-research-report">{decision.report}</pre><div className="aw-sources">{decision.sources.map(source => <a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.title}</a>)}</div></details></section>)}</div>;
}
