import { useState } from 'react';
import type { FormEvent } from 'react';
import { Store, Globe, Upload } from 'lucide-react';
import { agentApi, productionLabels } from '../services/agentApi';
import type { Workspace, ShopSettings, ProductionKind } from '../services/agentApi';

type Props = { workspace: Workspace; busy: boolean; mutate: (operation: () => Promise<Workspace>, success?: string) => Promise<Workspace | null> };
const formats = Object.keys(productionLabels) as ProductionKind[];
const money = (minor: number) => (minor / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
export function ShopPanel({ workspace, busy, mutate }: Props) {
  const shop = workspace.shop;
  const [key, setKey] = useState(''), [authorizeWebhook, setAuthorizeWebhook] = useState(false);
  const [settings, setSettings] = useState<ShopSettings>({ name: shop?.name || '', contact: shop?.contact || '', license: shop?.license || '', enabled: shop?.enabled || false, autoPublish: shop?.autoPublish || false, maxProducts: shop?.maxProducts || 20, prices: shop?.prices && Object.keys(shop.prices).length ? shop.prices : { text: 1500, image: 1500, thumbnail: 2500, sprites: 2500, model3d: 3500 } });
  async function connect(e: FormEvent) { e.preventDefault(); const result = await mutate(() => agentApi.connectShop(key, authorizeWebhook), 'Stripe conectada. Configure loja, preços e publicação abaixo.'); if (result) setKey(''); }
  async function configure(e: FormEvent) { e.preventDefault(); await mutate(() => agentApi.configureShop(settings), 'Loja configurada. Publicação automática, quando autorizada, vale por até 72 horas.'); }
  const ready = workspace.missions.filter(m => m.purpose !== 'experiment-preparation' && ['review', 'approved'].includes(m.status) && !shop?.products.some(p => p.missionId === m.id));
  return <section className="aw-panel" id="shop"><div className="aw-section-title"><div><p className="aw-eyebrow">PUBLICAÇÃO / TODOS OS FORMATOS</p><h2><Store size={21} /> Sua loja automática</h2></div><span className="aw-badge">{shop?.configured ? shop.livemode ? 'STRIPE REAL' : 'MODO TESTE' : 'CONECTAR PAGAMENTOS'}</span></div>
    <p className="aw-caption">Textos, imagens, thumbnails e packs 2D/3D viram produtos com página pública, preço por formato e ZIP para download após confirmação do pagamento. A publicação não atrai compradores por si só; conecte seus canais no painel Divulgação para automatizar os anúncios.</p>
    <details open={!shop?.configured}><summary>Conectar recebimento Stripe</summary><ol><li>Crie ou use sua conta Stripe. Conclua a ativação e configure a conta bancária na própria Stripe.</li><li>Copie a chave secreta no painel. Use uma chave de teste para validar sem dinheiro; use um espaço separado para vendas reais se já houver compras de teste.</li><li>Autorize abaixo o registro do webhook. A aplicação configura a confirmação de pagamentos automaticamente.</li></ol><a className="aw-button aw-secondary" href="https://dashboard.stripe.com/apikeys" target="_blank" rel="noreferrer">Abrir chaves Stripe</a><form className="aw-form" onSubmit={connect}><label>Chave secreta Stripe<input type="password" autoComplete="off" value={key} maxLength={1000} onChange={e => setKey(e.target.value)} placeholder="sk_live_… ou sk_test_…" required /></label><label className="aw-checkbox"><input type="checkbox" checked={authorizeWebhook} onChange={e => setAuthorizeWebhook(e.target.checked)} /> Autorizar conexão e registro do webhook de pagamentos desta loja na minha conta Stripe</label><small>A chave fica criptografada no servidor. Cadastros, dados bancários e tarifas são gerenciados na Stripe.</small><button className="aw-button" disabled={busy || !authorizeWebhook}>Conectar pagamentos</button></form></details>
    {shop?.configured && <><details><summary>Configurar preços, licença e publicação automática</summary><form className="aw-form" onSubmit={configure}><label>Nome público da loja<input value={settings.name} maxLength={100} onChange={e => setSettings(s => ({ ...s, name: e.target.value }))} required /></label><label>E-mail público de suporte<input type="email" value={settings.contact} maxLength={200} onChange={e => setSettings(s => ({ ...s, contact: e.target.value }))} required /></label><label>Licença e condições para os compradores<textarea rows={4} value={settings.license} maxLength={4000} onChange={e => setSettings(s => ({ ...s, license: e.target.value }))} placeholder="Descreva uso comercial, modificações, redistribuição, suporte e limitações…" required /></label><div className="aw-columns">{formats.map(kind => <label key={kind}>Preço: {productionLabels[kind]} (R$)<input type="number" min={5} max={10000} step="0.01" value={settings.prices[kind] / 100} onChange={e => setSettings(s => ({ ...s, prices: { ...s.prices, [kind]: Math.round(Number(e.target.value) * 100) } }))} required /></label>)}</div><small>Preços são definidos por você uma vez. Novos produtos usam estes valores; produtos e compras existentes preservam preço e arquivo originais.</small><label>Limite de produtos<input type="number" min={1} max={200} value={settings.maxProducts} onChange={e => setSettings(s => ({ ...s, maxProducts: Number(e.target.value) }))} required /></label><label className="aw-checkbox"><input type="checkbox" checked={settings.enabled} onChange={e => setSettings(s => ({ ...s, enabled: e.target.checked }))} /> Abrir catálogo público e aceitar novas compras</label><label className="aw-checkbox"><input type="checkbox" checked={settings.autoPublish} onChange={e => setSettings(s => ({ ...s, autoPublish: e.target.checked }))} /> Publicar automaticamente todas as entregas concluídas, inclusive as já existentes em revisão, sem manter a aba aberta</label><small>Os arquivos ficarão à venda sem sua revisão individual. A publicação automática termina após 72 horas ou no limite; a loja e os downloads das compras continuam funcionando. Código é entregue como protótipo, sem execução ou implantação automática.</small><button className="aw-button" disabled={busy}>Salvar loja e autorização</button></form></details>
      <div className="aw-actions"><a className="aw-button aw-secondary" href={`/loja/${shop.slug}`} target="_blank" rel="noreferrer"><Globe size={16} /> Abrir loja pública</a></div><p className="aw-caption">{shop.products.length}/{shop.maxProducts} produtos · publicação automática {shop.autoPublish ? 'autorizada' : 'pausada'}{shop.expiresAt ? ` até ${new Date(shop.expiresAt).toLocaleString('pt-BR')}` : ''}. Desmarque “Abrir catálogo” para suspender novas vendas; compras existentes mantêm acesso.</p>{shop.error && <p className="aw-error" role="alert">{shop.error}</p>}
      <h3>Pagamentos confirmados</h3><p>Compras reais: {shop.metrics.purchases} · Receita bruta: {money(shop.metrics.grossMinor)} · Reembolsos: {money(shop.metrics.refundedMinor)}</p><p className="aw-caption">Compras de teste: {shop.metrics.testPurchases}. Receita não desconta taxas, API, impostos ou divulgação e não representa lucro.</p>
      <h3>Produtos publicados</h3>{!shop.products.length && <p className="aw-caption">A loja ainda não tem produtos. Entregas concluídas aparecem automaticamente após sua autorização.</p>}{shop.products.map(p => <article className="aw-project" key={p.id}><h3>{p.title}</h3><p>{productionLabels[p.kind]} · {money(p.priceMinor)} · {p.listed ? 'Publicado' : 'Oculto'} · ZIP {(p.bytes / 1024).toFixed(0)} KB</p><div className="aw-actions"><a href={`/loja/${shop.slug}?produto=${p.id}`} target="_blank" rel="noreferrer">Ver oferta</a><button className="aw-button aw-secondary" disabled={busy} onClick={() => void mutate(() => agentApi.listShopProduct(p.id, !p.listed), p.listed ? 'Produto retirado do catálogo. Compras existentes preservadas.' : 'Produto publicado novamente.')}>{p.listed ? 'Retirar do catálogo' : 'Republicar'}</button></div></article>)}
      {!!ready.length && <><h3>Entregas disponíveis para publicar</h3>{ready.map(m => <article className="aw-project" key={m.id}><h3>{m.title}</h3><button className="aw-button" disabled={busy || !shop.enabled} onClick={() => void mutate(() => agentApi.publishShopProduct(m.id), 'Produto publicado na loja própria.')}><Upload size={15} /> Publicar agora</button></article>)}</>}
    </>}
  </section>;
}
