// <auto-generated />
using System;
using CreditoSimulador.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreditoSimulador.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802234218_AddCreditCatalogTables")]
    partial class AddCreditCatalogTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreditoSimulador.App.Data.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<decimal>("LimiteGlobal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("limite_global");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("IdCliente");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("CreditoSimulador.App.Data.Conta", b =>
                {
                    b.Property<int>("IdConta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_conta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConta"));

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("saldo");

                    b.HasKey("IdConta");

                    b.HasIndex("IdCliente");

                    b.ToTable("contas", (string)null);
                });

            modelBuilder.Entity("CreditoSimulador.App.Data.Contrato", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_contrato");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdContrato"));

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_parcelas");

                    b.Property<decimal>("TaxaJurosMensal")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("taxa_juros_mensal");

                    b.Property<string>("TipoAmortizacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_amortizacao");

                    b.Property<decimal>("ValorFinanciado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_financiado");

                    b.HasKey("IdContrato");

                    b.ToTable("contratos", (string)null);
                });

            modelBuilder.Entity("CreditoSimulador.App.Data.CreditLimitRequestEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("CarenciaMeses")
                        .HasColumnType("integer")
                        .HasColumnName("carencia_meses");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimento");

                    b.Property<string>("Garantias")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("garantias");

                    b.Property<string>("OfertaId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("oferta_id");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_parcelas");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorSolicitado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_solicitado");

                    b.HasKey("Id");

                    b.ToTable("credit_limit_requests", (string)null);
                });

            modelBuilder.Entity("CreditoSimulador.App.Data.CreditOfferEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<int>("CarenciaMaximaMeses")
                        .HasColumnType("integer")
                        .HasColumnName("carencia_maxima_meses");

                    b.Property<int>("CarenciaMinimaMeses")
                        .HasColumnType("integer")
                        .HasColumnName("carencia_minima_meses");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("DiaVencimentoMaximo")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimento_maximo");

                    b.Property<int>("DiaVencimentoMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimento_minimo");

                    b.Property<string>("Garantias")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("garantias");

                    b.Property<decimal>("LimiteMaximoCliente")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("limite_maximo_cliente");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("ParcelasMaximas")
                        .HasColumnType("integer")
                        .HasColumnName("parcelas_maximas");

                    b.Property<int>("ParcelasMinimas")
                        .HasColumnType("integer")
                        .HasColumnName("parcelas_minimas");

                    b.Property<decimal>("TaxaJurosMensal")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("taxa_juros_mensal");

                    b.Property<string>("TipoAmortizacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_amortizacao");

                    b.Property<decimal>("ValorMaximo")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_maximo");

                    b.Property<decimal>("ValorMinimo")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_minimo");

                    b.HasKey("Id");

                    b.ToTable("credit_offers", (string)null);
                });

            modelBuilder.Entity("CreditoSimulador.App.Data.Parcela", b =>
                {
                    b.Property<int>("IdParcela")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_parcela");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdParcela"));

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<int>("IdContrato")
                        .HasColumnType("integer")
                        .HasColumnName("id_contrato");

                    b.Property<int>("NumParcela")
                        .HasColumnType("integer")
                        .HasColumnName("num_parcela");

                    b.Property<string>("StatusPagamento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_pagamento");

                    b.Property<decimal>("ValorAmortizacao")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_amortizacao");

                    b.Property<decimal>("ValorJuros")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_juros");

                    b.Property<decimal>("ValorTotalParcela")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_total_parcela");

                    b.HasKey("IdParcela");

                    b.HasIndex("IdContrato");

                    b.ToTable("parcelas", (string)null);
                });

            modelBuilder.Entity("CreditoSimulador.App.Data.Conta", b =>
                {
                    b.HasOne("CreditoSimulador.App.Data.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CreditoSimulador.App.Data.Parcela", b =>
                {
                    b.HasOne("CreditoSimulador.App.Data.Contrato", "Contrato")
                        .WithMany("Parcelas")
                        .HasForeignKey("IdContrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("CreditoSimulador.App.Data.Contrato", b =>
                {
                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
