import { useCallback, useEffect, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import { Activity, Bot, Check, Cpu, Download, Layers, Pause, Play, Plus, Radio, Terminal, KeyRound, RefreshCw, X, Settings } from 'lucide-react';
import { agentApi, getAccessCode, restoreAccessCode, productionLabels } from '../services/agentApi';
import type { Workspace, Mission, MissionStatus, ProductionKind } from '../services/agentApi';
import '../workspace.css';
import { StationMap } from '../components/StationMap';
import { AutonomousProjects } from '../components/AutonomousProjects';

const labels: Record<MissionStatus, string> = { draft: 'Rascunho', queued: 'Na fila', running: 'Executando', review: 'Sua revisão', approved: 'Aprovada', failed: 'Falhou', cancelled: 'Cancelada' };
const presets = [
  { label: 'Mobília 3D', kind: 'model3d' as const, title: 'Mesa low poly original', brief: 'Crie uma mesa de madeira low poly com tampo e quatro pernas, em metros, altura 0,75m. Materiais originais simples, chão em y=0. Entregue GLB e OBJ com texturas e cena de demonstração.' },
  { label: 'Produtos digitais', kind: 'text' as const, title: 'Criar uma coleção original de produtos digitais', brief: 'Produza três conceitos originais de produtos digitais para quem organiza a rotina. Entregue o conteúdo de um produto completo, textos de apresentação e um plano de validação. Não invente demanda, preços de concorrentes ou vendas.' },
  { label: 'Thumbnails', kind: 'thumbnail' as const, title: 'Thumbnail original para YouTube', brief: 'Gere uma thumbnail original sobre montar uma central de agentes de IA. Visual tecnológico verde e preto, composição legível em celular, contraste alto e espaço para título curto. Não use marcas ou rostos de terceiros.' },
  { label: 'Pack 2D', kind: 'sprites' as const, title: 'Mobília 2D para uma estação futurista', brief: 'Produza quatro objetos separados: mesa, cadeira, armário e terminal. Estilo cartoon top-down, paleta verde escuro e cinza, iluminação superior consistente. PNGs transparentes, atlas e cena de demonstração para Godot. Inclua instruções para Unity.' },
  { label: 'Blog', kind: 'text' as const, title: 'Artigo sobre organizar trabalho com agentes', brief: 'Escreva um artigo original de 800 palavras para iniciantes sobre organização de tarefas com agentes de IA. Inclua exemplos, limites práticos e checklist. Não invente pesquisas, links, resultados financeiros ou experiências pessoais.' },
  { label: 'Protótipo', kind: 'text' as const, title: 'Criar um pequeno jogo de navegador', brief: 'Entregue um arquivo HTML completo, com CSS e JavaScript incorporados, de um jogo simples de coletar energia em uma estação espacial. Controles por teclado e botões de toque. Sem bibliotecas externas. Explique como salvar e abrir. Não afirme que o código foi testado.' },
];
function errorMessage(error: unknown) { return error instanceof Error ? error.message : 'Não foi possível concluir a ação.'; }
function download(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }


function Artifact({ mission }: { mission: Mission }) {
  const [asset, setAsset] = useState<{ url: string; preview: string } | null>(null);
  const [error, setError] = useState('');
  useEffect(() => {
    let active = true; const urls: string[] = [];
    const create = (blob: Blob) => { const url = URL.createObjectURL(blob); urls.push(url); return url; };
    Promise.all([agentApi.image(mission.id), mission.hasPreview ? agentApi.image(mission.id, true) : Promise.resolve(null)]).then(([blob, preview]) => {
      if (!active) return;
      const url = create(blob); setAsset({ url, preview: preview ? create(preview) : blob.type.startsWith('image/') ? url : '' });
    }).catch(error => { if (active) setError(errorMessage(error)); });
    return () => { active = false; urls.forEach(url => URL.revokeObjectURL(url)); };
  }, [mission.id, mission.hasPreview]);
  return <div className="aw-artifact">{error ? <p role="alert">{error}</p> : asset ? <>{asset.preview && <img src={asset.preview} alt={`Prévia dos arquivos de ${mission.title}; confira antes de usar`} />}<a className="aw-button" href={asset.url} download={mission.artifactFilename || `hubloan-${mission.id}.png`}><Download size={16} /> {mission.artifactMime === 'application/zip' ? 'Baixar pacote ZIP' : 'Baixar PNG'}</a></> : <p>Carregando arquivos…</p>}</div>;
}

export function AgentWorkspacePage() {
  const [workspace, setWorkspace] = useState<Workspace | null>(null);
  const [connectionError, setConnectionError] = useState('');
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const epoch = useRef(0);
  const busyRef = useRef(false);
  const [title, setTitle] = useState(''), [brief, setBrief] = useState(''), [agentId, setAgentId] = useState('research');
  const [kind, setKind] = useState<ProductionKind>('text'), [execute, setExecute] = useState(true);
  const [agentName, setAgentName] = useState(''), [agentRole, setAgentRole] = useState('');
  const [filter, setFilter] = useState('all'), [selectedId, setSelectedId] = useState('');
  const [apiKey, setApiKey] = useState(''), [model, setModel] = useState(''), [imageModel, setImageModel] = useState('');
  const [restoreCode, setRestoreCode] = useState('');
  const refresh = useCallback(async () => {
    if (busyRef.current) return;
    const stamp = ++epoch.current;
    try { const data = await agentApi.workspace(); if (epoch.current === stamp) { setWorkspace(data); setConnectionError(''); } }
    catch (error) { if (epoch.current === stamp) setConnectionError(errorMessage(error)); }
  }, []);
  useEffect(() => {
    document.title = 'HubLoan · Central de agentes';
    let alive = true; let timer: ReturnType<typeof setTimeout>;
    async function poll() { await refresh(); if (alive) timer = setTimeout(poll, 4000); }
    void poll();
    return () => { alive = false; clearTimeout(timer);
      // Invalidate pending network responses; this ref is a request counter, not a DOM node.
      // eslint-disable-next-line react-hooks/exhaustive-deps
      epoch.current++;
    };
  }, [refresh]);
  async function mutate(operation: () => Promise<Workspace>, success = '') {
    if (busyRef.current) return null;
    busyRef.current = true; setBusy(true); epoch.current++; setMessage('');
    try { const data = await operation(); setWorkspace(data); setConnectionError(''); setMessage(success); return data; }
    catch (error) { setMessage(errorMessage(error)); return null; }
    finally { busyRef.current = false; setBusy(false); }
  }
  async function submitMission(event: FormEvent) {
    event.preventDefault();
    const data = await mutate(() => agentApi.addMission(title, brief, agentId, kind, execute && Boolean(workspace?.settings.configured)), execute && workspace?.settings.configured ? 'Missão na fila. A execução começa automaticamente no servidor.' : 'Rascunho salvo. Conecte a IA para executar.');
    if (data) { setSelectedId(data.missions[0].id); setTitle(''); setBrief(''); setFilter('all'); }
  }
  async function submitAgent(event: FormEvent) { event.preventDefault(); const data = await mutate(() => agentApi.addAgent(agentName, agentRole), 'Agente cadastrado.'); if (data) { setAgentId(data.agents[data.agents.length - 1].id); setAgentName(''); setAgentRole(''); } }
  async function connect(event: FormEvent) { event.preventDefault(); const data = await mutate(() => agentApi.saveSettings(apiKey, model || workspace!.settings.model, imageModel || workspace!.settings.imageModel), 'Conexão salva. As novas missões podem executar automaticamente.'); if (data) setApiKey(''); }
  async function restore(event: FormEvent) { event.preventDefault(); try { restoreAccessCode(restoreCode); epoch.current++; setWorkspace(null); setSelectedId(''); setRestoreCode(''); await refresh(); setMessage('Espaço restaurado pelo código de acesso.'); } catch (error) { setMessage(errorMessage(error)); } }
  const selected = workspace?.missions.find(mission => mission.id === selectedId);
  const enabled = workspace?.agents.filter(agent => agent.enabled).length || 0;
  const running = workspace?.missions.filter(mission => mission.status === 'running') || [];
  const filtered = workspace?.missions.filter(mission => filter === 'all' || mission.status === filter) || [];
  return <div className="agent-workspace">
    <aside className="aw-sidebar"><a className="aw-brand" href="#overview"><span><Cpu size={22} /></span><div>HUBLOAN<small>AGENT OPERATING SYSTEM</small></div></a><p className="aw-eyebrow">SUA ESTAÇÃO DE TRABALHO</p><nav aria-label="Navegação"><a href="#station"><Layers size={18} /> Estação</a><a href="#autonomy"><Cpu size={18} /> Autonomia</a><a href="#agents"><Bot size={18} /> Agentes</a><a href="#missions"><Activity size={18} /> Missões</a><a href="#settings"><Settings size={18} /> Conectar IA</a></nav><div className="aw-sidebar-bottom"><Radio size={17} /><div>{workspace?.settings.configured ? 'IA conectada' : 'Aguardando conexão'}<small>{running.length ? 'Missão em execução' : 'Sem execução ativa'}</small></div></div></aside>
    <main className="aw-main" id="overview"><header className="aw-topbar"><span>CENTRAL DE OPERAÇÕES / ESTAÇÃO</span><span className="aw-badge">{connectionError ? 'SEM CONEXÃO' : workspace ? 'SERVIDOR CONECTADO' : 'CONECTANDO'}</span></header>
      <section className="aw-heading"><div><p className="aw-eyebrow">UMA IDEIA. UMA ENTREGA REAL.</p><h1>Uma estação que trabalha<span>.</span></h1><p>Defina os limites. Orion descobre oportunidades, escolhe a próxima entrega e os robôs acompanham a execução.</p></div><button className="aw-button aw-secondary" disabled={!workspace} onClick={() => download(new Blob([JSON.stringify(workspace, null, 2)], { type: 'application/json' }), 'hubloan-entregas.json')}><Download size={16} /> Exportar histórico</button></section>
      <div className="aw-notice"><Radio size={18} /><p>{workspace?.settings.configured ? 'Novas missões podem executar no servidor, mesmo com esta aba fechada, enquanto o servidor estiver ativo. Cada entrega exige sua revisão.' : 'Conecte uma chave da OpenAI uma vez para ativar a execução. Você já pode organizar os briefings. A API é cobrada separadamente do ChatGPT.'}</p></div>
      {connectionError && <div className="aw-error" role="alert">{connectionError} <button className="aw-button aw-secondary" onClick={() => void refresh()}><RefreshCw size={14} /> Tentar novamente</button></div>}
      <p className="aw-feedback" role="status">{busy ? 'Salvando no servidor…' : message}</p>
      {!workspace && <div className="aw-panel aw-empty"><Cpu size={30} /><h2>Conectando sua central</h2><p>O primeiro acesso pode demorar se a hospedagem estiver iniciando.</p><details><summary>Restaurar espaço com código de acesso</summary><form className="aw-form" onSubmit={restore}><label>Código<input type="password" value={restoreCode} onChange={e => setRestoreCode(e.target.value)} required /></label><button className="aw-button">Restaurar</button></form></details></div>}
      {workspace && <>
      <section className="aw-metrics" aria-label="Indicadores reais">{[
        { label: 'AGENTES DISPONÍVEIS', value: enabled, detail: 'Funções configuradas', icon: Bot },
        { label: 'EXECUÇÕES ATIVAS', value: running.length, detail: `${workspace.missions.filter(m => m.status === 'queued').length} na fila`, icon: Activity },
        { label: 'PARA SUA REVISÃO', value: workspace.missions.filter(m => m.status === 'review').length, detail: 'Entregas aguardando aprovação', icon: Check },
        { label: 'TOKENS REGISTRADOS', value: (workspace.missions.reduce((n, m) => n + m.tokens, 0) + (workspace.autonomy?.projects || []).reduce((n, p) => n + p.tokens, 0)).toLocaleString('pt-BR'), detail: `${workspace.missions.reduce((n, m) => n + m.images, 0)} imagens concluídas · não é valor em R$`, icon: Cpu },
      ].map(metric => <article className="aw-metric" key={metric.label}><div><span>{metric.label}</span><metric.icon size={18} /></div><strong>{metric.value}</strong><small>{metric.detail}</small></article>)}</section>
      <section className="aw-panel" id="station"><div className="aw-section-title"><div><p className="aw-eyebrow">VISUALIZAÇÃO DA OPERAÇÃO</p><h2>A estação</h2></div><span className="aw-badge">{running.length ? 'ATIVIDADE REAL' : 'EM ESPERA'}</span></div><StationMap workspace={workspace} onSelect={setSelectedId} /><p className="aw-caption">Cada robô representa uma função de IA. Ele muda de sala quando a tarefa muda de etapa; sem atividade, aguarda. A estação não registra vendas ou receitas sem integração.</p></section>
      <AutonomousProjects workspace={workspace} busy={busy} mutate={mutate} />
      <div className="aw-columns"><section className="aw-panel" id="agents"><div className="aw-section-title"><div><p className="aw-eyebrow">EQUIPE</p><h2>Seus agentes</h2></div><Bot size={22} /></div><div className="aw-agent-list">{workspace.agents.map(agent => <article className="aw-agent" key={agent.id}><span className="aw-avatar">{agent.name.slice(0, 2).toUpperCase()}</span><div><h3>{agent.name}</h3><p>{agent.role}</p><small>{running.some(m => m.agentId === agent.id) ? 'EXECUTANDO' : agent.enabled ? 'DISPONÍVEL' : 'NOVAS TAREFAS PAUSADAS'}</small></div><button className="aw-icon-button" disabled={busy} aria-label={`${agent.enabled ? 'Pausar novas tarefas de' : 'Reativar'} ${agent.name}`} onClick={() => void mutate(() => agentApi.toggleAgent(agent.id, !agent.enabled))}>{agent.enabled ? <Pause size={17} /> : <Play size={17} />}</button></article>)}</div><form className="aw-form aw-agent-form" onSubmit={submitAgent}><h3>Adicionar função de agente</h3><label>Nome<input value={agentName} onChange={e => setAgentName(e.target.value)} maxLength={40} required /></label><label>Função<input value={agentRole} onChange={e => setAgentRole(e.target.value)} maxLength={100} required /></label><button className="aw-button aw-secondary" disabled={busy}><Plus size={16} /> Cadastrar</button></form></section>
      <section className="aw-panel"><div className="aw-section-title"><div><p className="aw-eyebrow">NOVA MISSÃO</p><h2>O que vamos produzir?</h2></div><Plus size={22} /></div><div className="aw-presets">{presets.map(preset => <button className="aw-button aw-secondary" key={preset.label} onClick={() => { setTitle(preset.title); setBrief(preset.brief); setKind(preset.kind); }}>{preset.label}</button>)}</div><form className="aw-form" onSubmit={submitMission}><label>Título<input value={title} onChange={e => setTitle(e.target.value)} maxLength={100} required /></label><label>Briefing<textarea value={brief} onChange={e => setBrief(e.target.value)} rows={5} maxLength={6000} placeholder="Objetivo, público e entrega esperada…" required /><small>{brief.length}/6.000</small></label><label>Entrega<select value={kind} onChange={e => setKind(e.target.value as ProductionKind)}>{Object.entries(productionLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Responsável<select value={agentId} onChange={e => setAgentId(e.target.value)}>{workspace.agents.map(agent => <option key={agent.id} value={agent.id} disabled={!agent.enabled}>{agent.name} · {agent.role}</option>)}</select></label><label className="aw-checkbox"><input type="checkbox" checked={execute} disabled={!workspace.settings.configured} onChange={e => setExecute(e.target.checked)} /> Executar automaticamente ao criar</label><small className="aw-caption">{kind === 'thumbnail' ? '4 chamadas: plano, direção, fundo e revisão visual. Informe assunto, público e resumo do vídeo no briefing.' : kind === 'sprites' ? '7 chamadas: plano, estilo, quatro objetos e revisão visual.' : kind === 'model3d' ? '2 chamadas de texto; geometria e texturas são construídas no servidor.' : kind === 'image' ? 'Duas etapas de texto e uma geração de imagem.' : 'Três etapas de texto: plano, produção e revisão.'} Chamadas usam a sua chave e podem gerar custos.</small><button className="aw-button" disabled={busy || !enabled}><Play size={17} /> {workspace.settings.configured && execute ? 'Criar e executar' : 'Salvar rascunho'}</button></form></section></div>
      <section className="aw-panel" id="missions"><div className="aw-section-title"><div><p className="aw-eyebrow">PIPELINE</p><h2>Missões e entregas</h2></div><label className="aw-filter">Filtrar<select value={filter} onChange={e => setFilter(e.target.value)}><option value="all">Todas</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>{!filtered.length ? <div className="aw-empty"><Layers size={28} /><h3>Nenhuma missão aqui</h3><p>Escolha um exemplo ou descreva sua própria entrega.</p></div> : <div className="aw-missions">{filtered.map(m => <article className="aw-mission" key={m.id}><div><h3>{m.title}</h3><small>{workspace.agents.find(a => a.id === m.agentId)?.name} · {productionLabels[m.kind]} · {m.phase}</small></div><span className={`aw-status aw-status-${m.status}`}>{labels[m.status]}</span><div className="aw-actions"><button className="aw-button aw-secondary" onClick={() => setSelectedId(m.id)}>Detalhes</button>{['draft', 'failed', 'cancelled'].includes(m.status) && <button className="aw-button" disabled={busy || !workspace.settings.configured || !workspace.agents.find(a => a.id === m.agentId)?.enabled} onClick={() => void mutate(() => agentApi.action(m.id, 'run'), 'Missão na fila.')}><Play size={14} /> {m.status === 'draft' ? 'Executar' : 'Tentar novamente'}</button>}{['queued', 'running'].includes(m.status) && <button className="aw-button aw-secondary" disabled={busy} onClick={() => void mutate(() => agentApi.action(m.id, 'cancel'), 'Cancelada. Chamadas já enviadas podem ter sido cobradas.')}><X size={14} /> Cancelar</button>}{m.status === 'review' && <button className="aw-button" disabled={busy} onClick={() => void mutate(() => agentApi.action(m.id, 'approve'), 'Entrega aprovada por você.')}><Check size={14} /> Aprovar</button>}</div></article>)}</div>}</section>
      <section className="aw-panel aw-terminal" id="terminal"><div className="aw-section-title"><div><p className="aw-eyebrow">SAÍDA DA MISSÃO</p><h2><Terminal size={19} /> Entrega e registro</h2></div>{selected?.output && <button className="aw-button aw-secondary" onClick={() => download(new Blob([selected.output], { type: 'text/markdown;charset=utf-8' }), `hubloan-${selected.id}.md`)}><Download size={15} /> Baixar texto</button>}</div>{selected ? <><h3>{selected.title} · {labels[selected.status]}</h3>{selected.error && <p className="aw-error" role="alert">{selected.error}</p>}{selected.hasArtifact && <Artifact key={selected.id} mission={selected} />}<details><summary>Briefing original</summary><pre>{selected.brief}</pre></details><pre>{selected.output || selected.phase}</pre><div className="aw-log">{selected.events.map((event, index) => <p key={index}><time>{new Date(event.at).toLocaleTimeString('pt-BR')}</time> {event.message}</p>)}</div><p className="aw-caption">{selected.tokens.toLocaleString('pt-BR')} tokens registrados · {selected.images} imagens concluídas · tentativa {selected.attempt}. O painel do provedor é a referência de cobrança.</p></> : <p>Selecione Detalhes em uma missão para ver a entrega e as etapas reais.</p>}</section>
      <section className="aw-panel" id="settings"><div className="aw-section-title"><div><p className="aw-eyebrow">CONEXÃO</p><h2><KeyRound size={20} /> Ativar sua IA</h2></div><span className="aw-badge">{workspace.settings.configured ? 'CHAVE SALVA' : 'SEM CHAVE'}</span></div><form className="aw-form" onSubmit={connect}><label>Chave da OpenAI<input type="password" value={apiKey} onChange={e => setApiKey(e.target.value)} placeholder={workspace.settings.configured ? 'Preencha apenas para trocar a chave' : 'sk-…'} autoComplete="off" required={!workspace.settings.configured} maxLength={1000} /></label><div className="aw-columns"><label>Modelo de texto<select value={model || workspace.settings.model} onChange={e => setModel(e.target.value)}><option value="gpt-4.1-mini">GPT-4.1 mini · econômico</option><option value="gpt-4.1">GPT-4.1</option></select></label><label>Modelo de imagem<select value={imageModel || workspace.settings.imageModel} onChange={e => setImageModel(e.target.value)}><option value="gpt-image-1-mini">GPT Image 1 mini · econômico</option><option value="gpt-image-1.5">GPT Image 1.5</option></select></label></div><div className="aw-actions"><button className="aw-button" disabled={busy}><Radio size={16} /> {workspace.settings.configured ? 'Salvar conexão' : 'Conectar e ativar'}</button>{workspace.settings.configured && <button className="aw-button aw-secondary" type="button" disabled={busy} onClick={() => void mutate(agentApi.disconnect, 'Chave removida e fila cancelada.')}>Desconectar e cancelar fila</button>}<a className="aw-button aw-secondary" href="https://platform.openai.com/api-keys" target="_blank" rel="noreferrer">Criar chave</a></div></form><p className="aw-caption">A chave fica criptografada no servidor e não volta para a interface. Imagens podem exigir verificação da organização na OpenAI. Limite gastos no painel do provedor. Pesquisa web pode ser ativada nos projetos autônomos e tem cobrança adicional. Publicação, pagamentos e execução de código não estão conectados.</p><details className="aw-access"><summary>Acesso em outro celular e backup</summary><p>Este navegador guarda seu código de acesso. Baixe e guarde como uma senha: ele permite acessar suas missões e usar a chave conectada. Sem o código, não há recuperação deste espaço.</p><button className="aw-button aw-secondary" onClick={() => { try { download(new Blob([getAccessCode()], { type: 'text/plain' }), 'hubloan-codigo-de-acesso.txt'); } catch (error) { setMessage(errorMessage(error)); } }}><Download size={16} /> Guardar código de acesso</button><form className="aw-form" onSubmit={restore}><label>Restaurar outro espaço<input type="password" value={restoreCode} onChange={e => setRestoreCode(e.target.value)} required maxLength={64} /></label><button className="aw-button aw-secondary" disabled={busy}>Restaurar espaço</button></form></details></section>
      <footer className="aw-footer"><span>HubLoan · dados no {workspace.storage === 'postgres' ? 'PostgreSQL' : 'servidor local SQLite'}</span><span>Servidor inativo pausa o trabalho. Projetos autorizados retomam tarefas pendentes ao voltar.</span></footer>
      </>}
    </main>
  </div>;
}
