import test from 'node:test';
import assert from 'node:assert/strict';
import {createStore} from '../store.mjs';
import {createEtsy,publicEtsy,createEtsyProvider} from '../etsy.mjs';
import {workspaceId,publicWorkspace} from '../domain.mjs';
import {createExperiment,experimentAction,publicExperiments} from '../experiments.mjs';
const id=workspaceId('a'.repeat(64)),masterKey='f'.repeat(64),now=Date.now(),money=n=>({amount:n,divisor:100,currency_code:'BRL'});
async function fixture(t,fail=false,currency='BRL'){
 const store=await createStore({file:':memory:'}),calls=[];let receipts=[];
 const provider={token:async()=>({access_token:'11.secret-access',refresh_token:'11.secret-refresh',expires_in:3600,scope:'shops_r listings_r listings_w transactions_r'}),get:async(_c,_a,p)=>{calls.push(['get',p]);if(p.startsWith('users/'))return{shop_id:22,shop_name:'Fixture',currency_code:currency};if(p.includes('receipts?'))return{count:receipts.length,results:receipts};return{shop_id:22,listing_id:33,title:'Original pack',state:'active'};},post:async(_c,_a,p,b)=>{calls.push(['post',p,b]);if(p.endsWith('/listings'))return{listing_id:33};if(fail)throw new Error('RAW TOKEN must not leak');return{};},patch:async()=>({listing_id:33,state:'active'})};
 const etsy=createEtsy(store,{masterKey,provider});t.after(()=>store.close());await etsy.configure(id,{clientId:'client',sharedSecret:'secret-fixture',shopId:22});const auth=await etsy.authorize(id),state=new URL(auth.url).searchParams.get('state');await etsy.callback(state,'code');
 let eid;await store.mutate(id,w=>{const e=createExperiment(w,{name:'Original pack',hypothesis:'Original UI',audience:'Creators',channel:'Etsy',budgetMinor:5000,days:7,minSales:1,minNetMinor:1,missionIds:[],salesChannel:{factoryId:'factory-sprites',channel:'etsy'}},now);eid=e.id;
 for(const [a,i]of [['validation-evidence',{url:'https://example.com/request',summary:'Demand fixture',observedAt:new Date(now).toISOString()}],['validation-offer',{scope:'Four original icons',criteria:'Own silhouettes',priceMinor:1000,deliveryDays:2}],['marketplace-offer',{factoryId:'factory-sprites',channel:'etsy',title:'Original pack',description:'Own design',tags:'icons, game ui',license:'Own rights'}],['validation-sample',{kind:'sprites',agentId:'creator',allowImages:true}]])experimentAction(w,eid,a,i,now);
 const m=w.missions[0];m.status='review';m.output='Original';m.artifact={base64:'dGVzdA==',preview:'dGVzdA==',mime:'application/zip',filename:'icons.zip'};experimentAction(w,eid,'validation-quality',{approved:true,reason:'Reviewed sample'},now);experimentAction(w,eid,'originality-review',{approved:true,reason:'Reviewed original design'},now);});
 return{store,etsy,calls,eid,state,read:async()=>(await store.read(id)).workspace,setReceipts:r=>receipts=r,publish:()=>etsy.publish(id,eid,{authorize:true,eligible:true,taxonomyId:1,priceMinor:1000})};
}
test('OAuth PKCE state is single-use; secrets encrypted and excluded from workspace response',async t=>{const f=await fixture(t),w=await f.read();assert.equal(publicEtsy(w).connected,true);assert.equal(JSON.stringify(w.etsy).includes('secret-access'),false);assert.equal(JSON.stringify(publicWorkspace(w,'sqlite')).includes('secret-refresh'),false);await assert.rejects(()=>f.etsy.callback(f.state,'again'),/já utilizada/);await assert.rejects(()=>f.etsy.callback('bad','code'),/inválido/);});
test('Etsy requires authorization and exact approvals; publishes one listing with auto renew off',async t=>{const f=await fixture(t);await assert.rejects(()=>f.etsy.publish(id,f.eid,{eligible:true,taxonomyId:1,priceMinor:1000}),/Confirme/);await f.publish();const w=await f.read();assert.equal(w.experiments[0].marketplace.publication.origin,'etsy-api');assert.equal(w.experiments[0].marketplace.observation,undefined);const draft=f.calls.find(c=>c[0]==='post'&&c[1].endsWith('/listings'));assert.equal(draft[2].get('should_auto_renew'),'false');assert.equal(draft[2].get('type'),'download');await assert.rejects(()=>f.publish(),/já publicada/);assert.equal(f.calls.filter(c=>c[0]==='post'&&c[1].endsWith('/listings')).length,1);});
test('uncertain upload cannot be repeated; state reconciles via official API and errors redacted',async t=>{const f=await fixture(t,true);await assert.rejects(()=>f.publish());let w=await f.read();assert.equal(w.experiments[0].marketplace.etsy.status,'uncertain');assert.equal(w.experiments[0].marketplace.etsy.listingId,33);assert.equal(JSON.stringify(publicWorkspace(w,'sqlite')).includes('RAW TOKEN'),false);await assert.rejects(()=>f.publish(),/já iniciado/);await f.etsy.reconcile(id,f.eid,{});w=await f.read();assert.equal(w.experiments[0].marketplace.publication.origin,'etsy-api');assert.equal(f.calls.filter(c=>c[0]==='post'&&c[1].endsWith('/listings')).length,1);});
const receipt={receipt_id:44,is_paid:true,status:'paid',transactions:[{listing_id:33,quantity:1}],refunds:[],total_price:money(1000),discount_amt:money(0)};
test('Etsy period sync deduplicates and replaces totals; mixed/refunded/foreign orders require reconciliation',async t=>{const f=await fixture(t);await f.publish();f.setReceipts([receipt,receipt]);await f.etsy.sync(id,f.eid);let e=publicExperiments(await f.read())[0];assert.equal(e.marketplaceMetrics.grossMinor,1000);assert.equal(e.marketplaceMetrics.sales,1);assert.equal(e.marketplaceMetrics.visits,null);assert.equal(e.marketplaceMetrics.resultMinor,null);await f.etsy.sync(id,f.eid);assert.equal((await f.read()).experiments[0].marketplace.observation.grossMinor,1000);f.setReceipts([{...receipt,refunds:[{amount:500}]}]);await f.etsy.sync(id,f.eid);assert.equal(publicExperiments(await f.read())[0].marketplaceMetrics,null);f.setReceipts([{...receipt,transactions:[...receipt.transactions,{listing_id:999,quantity:1}]}]);await f.etsy.sync(id,f.eid);assert.equal(publicExperiments(await f.read())[0].marketplaceMetrics,null);const g=await fixture(t,false,'USD');await g.publish();g.setReceipts([{...receipt,total_price:{amount:1000,divisor:100,currency_code:'USD'}}]);await g.etsy.sync(id,g.eid);assert.equal(publicExperiments(await g.read())[0].marketplaceMetrics,null);});
test('fixed official API origin, credential headers, rate-limit redaction and no retry',async()=>{let calls=0;const p=createEtsyProvider(async(url,o)=>{calls++;assert.ok(url.startsWith('https://api.etsy.com/v3/'));assert.equal(o.headers['x-api-key'],'client:secret');assert.equal(o.redirect,'error');return new Response('RAW TOKEN',{status:429});});await assert.rejects(()=>p.get({clientId:'client',sharedSecret:'secret'},'access','shops/22'),/Limite Etsy/);assert.equal(calls,1);});
test('changing reviewed sample/preview or stale evidence blocks before any Etsy creation',async t=>{
 const f=await fixture(t);await f.store.mutate(id,w=>{w.missions[0].artifact.preview='Y2hhbmdlZA==';});await assert.rejects(()=>f.publish(),/originalidade/);assert.equal(f.calls.filter(c=>c[0]==='post').length,0);
 const g=await fixture(t);await g.store.mutate(id,w=>{w.experiments[0].validation.evidence.observedAt='2020-01-01T00:00:00Z';});await assert.rejects(()=>g.publish(),/evidência/);assert.equal(g.calls.filter(c=>c[0]==='post').length,0);
});
