import test from 'node:test';
import assert from 'node:assert/strict';
import { initialWorkspace } from '../domain.mjs';
import { createExperiment, experimentAction, publicExperiments } from '../experiments.mjs';
import { validationPublicationAllowed } from '../validation.mjs';
import { commercialLearning } from '../learning.mjs';
const now=Date.now();
function fixture(){const w=initialWorkspace();const e=createExperiment(w,{name:'Primeira oferta',hypothesis:'Testar utilidade',audience:'Freelancers',channel:'Canal próprio',days:7,budgetMinor:6000,minSales:1,minNetMinor:1000,missionIds:[]},now);const act=(a,i={})=>experimentAction(w,e.id,`validation-${a}`,i,now);act('enable');return {w,e,act};}
function sample(f){f.act('evidence',{url:'https://example.org/request',summary:'Pedido observado de template',observedAt:new Date(now).toISOString()});f.act('offer',{scope:'Um template original',criteria:'Legível e utilizável',priceMinor:2000,deliveryDays:3});f.act('sample',{agentId:'creator',kind:'text'});return f.w.missions[0];}
test('validation requires evidence and offer, creates only one draft and cannot adopt an unrelated mission',()=>{const f=fixture();assert.throws(()=>f.act('sample',{agentId:'creator',kind:'text'}),/evidência/);assert.throws(()=>f.act('evidence',{url:'javascript:alert(1)',summary:'x',observedAt:new Date(now).toISOString()}),/URL/);assert.throws(()=>f.act('evidence',{url:'https://example.org',summary:'x',observedAt:new Date(now+86400000).toISOString()}),/30 dias/);const m=sample(f);assert.equal(m.status,'draft');assert.equal(m.tokens,0);assert.equal(f.e.missionIds[0],m.id);assert.throws(()=>f.act('sample',{agentId:'creator',kind:'text'}),/só há uma/);assert.throws(()=>experimentAction(f.w,f.e.id,'link',{missionId:'anything'},now),/somente a amostra/);});
test('quality and release bind the exact sample and proposed price, and do not authorize itch.io',()=>{const f=fixture(),m=sample(f);assert.throws(()=>f.act('quality',{approved:true,reason:'Li'}),/Produza/);m.status='review';m.output='Sample v1';f.w.shop={prices:{text:2000}};assert.equal(validationPublicationAllowed(f.w,m),false);f.act('quality',{approved:true,reason:'Conferi legibilidade e utilidade'});assert.equal(validationPublicationAllowed(f.w,m),false);f.act('release',{authorize:true});assert.equal(validationPublicationAllowed(f.w,m),true);assert.equal(validationPublicationAllowed(f.w,m,'itchio'),false);m.output='Sample v2';assert.equal(validationPublicationAllowed(f.w,m),false);assert.throws(()=>f.act('release',{authorize:true}),/versão/);m.output='Sample v1';f.w.shop.prices.text=3000;assert.equal(validationPublicationAllowed(f.w,m),false);f.w.shop.prices.text=2000;f.act('quality',{approved:false,reason:'Falhou em revisão posterior'});assert.equal(validationPublicationAllowed(f.w,m),false);});
test('declared interest never becomes sales; silence cannot invent a rejection reason',()=>{const f=fixture();sample(f);f.act('feedback',{outcome:'interested',reason:'Relatou interesse, não pagou'});f.act('feedback',{outcome:'rejected',reason:'Relatou preço alto'});f.act('feedback',{outcome:'no-response',reason:'Com certeza achou caro'});const e=publicExperiments(f.w,now)[0];assert.equal(e.metrics.sales,0);assert.equal(e.metrics.grossMinor,0);assert.equal(e.validation.feedback[0].reason,'Sem resposta; motivo desconhecido.');const memory=commercialLearning(f.w,now).experiments[0].validation;assert.equal(memory.feedbackCounts.interested,1);assert.ok(memory.reportedFeedback.some(f=>f.reason==='Relatou preço alto'));assert.equal(e.validationReadiness.canConsiderRepeating,false);});
test('recommendation requires current quality, real retained sale and reviewed costs; refunds invalidate it',()=>{const f=fixture(),m=sample(f);m.status='review';m.output='Sample';f.act('quality',{approved:true,reason:'Conferido'});f.w.shop={products:[{id:'p',missionId:m.id}],orders:[{id:'o',productId:'p',livemode:true,currency:'brl',status:'paid',priceMinor:2000,paidAt:new Date(now).toISOString()}]};assert.equal(publicExperiments(f.w,now)[0].validationReadiness.canConsiderRepeating,false);experimentAction(f.w,f.e.id,'cost',{category:'api',amountMinor:100,note:'Consumo atribuído'},now);experimentAction(f.w,f.e.id,'review',{complete:true},now);assert.equal(publicExperiments(f.w,now)[0].validationReadiness.canConsiderRepeating,true);f.w.shop.orders[0].refundedMinor=2000;assert.equal(publicExperiments(f.w,now)[0].validationReadiness.canConsiderRepeating,false);});
test('closed or expired experiments cannot release or publish another sample',()=>{const f=fixture(),m=sample(f);m.status='review';m.output='Sample';f.w.shop={prices:{text:2000}};f.act('quality',{approved:true,reason:'Conferido'});f.act('release',{authorize:true});assert.equal(validationPublicationAllowed(f.w,m,'shop',now+8*86400000),false);experimentAction(f.w,f.e.id,'close',{},now);assert.equal(validationPublicationAllowed(f.w,m),false);assert.throws(()=>f.act('release',{authorize:true}),/encerrada/);});
test('itch sample release binds reviewed bytes, destination, license and expiry without authorizing shop',()=>{
 const w=initialWorkspace();const e=createExperiment(w,{name:'2D test',hypothesis:'Small asset pack',audience:'Developers',channel:'itch.io',days:7,budgetMinor:3000,minSales:1,minNetMinor:1,missionIds:[],salesChannel:{factoryId:'factory-sprites',channel:'itchio'}},now);
 const act=(a,i={})=>experimentAction(w,e.id,a,i,now);
 act('validation-evidence',{url:'https://example.org/request',summary:'Request for assets',observedAt:new Date(now).toISOString()});act('validation-offer',{scope:'One sample',criteria:'Usable asset',priceMinor:1000,deliveryDays:2});
 assert.throws(()=>act('validation-sample',{kind:'text',agentId:'creator'}),/formato/);
 act('validation-sample',{kind:'sprites',agentId:'creator',allowImages:true});const m=w.missions[0];assert.equal(m.factoryId,'factory-sprites');assert.equal(m.status,'draft');
 m.status='review';m.artifact={mime:'application/zip',base64:'UEs=',filename:'sample.zip'};
 act('marketplace-offer',{factoryId:'factory-sprites',channel:'itchio',title:'Small pack',description:'One reviewed pack',tags:'2d',license:'Original'});
 w.commerce={secret:{},targets:{sprites:{id:1,url:'https://maker.itch.io/pack'}},license:'Original'};
 assert.throws(()=>act('validation-itch-release',{authorize:true}),/Revise/);act('validation-quality',{approved:true,reason:'Reviewed pack'});act('validation-itch-release',{authorize:true});
 assert.equal(validationPublicationAllowed(w,m,'itchio',now),true);assert.equal(validationPublicationAllowed(w,m,'shop',now),false);assert.equal(validationPublicationAllowed(w,m,'itchio',now+73*3600000),false);
 w.commerce.targets.sprites.url='https://maker.itch.io/other';assert.equal(validationPublicationAllowed(w,m,'itchio',now),false);w.commerce.targets.sprites.url='https://maker.itch.io/pack';
 w.commerce.license='Changed';assert.equal(validationPublicationAllowed(w,m,'itchio',now),false);w.commerce.license='Original';m.artifact.base64='Changed';assert.equal(validationPublicationAllowed(w,m,'itchio',now),false);
});
